### ISSUE TITLE
Compatability Question - USync Complete + uSync.ContentMappers

### ISSUE THREAD

**Issue by JohnBergman** [Jumoo/uSync.Complete.Issues#102]
Looking at the nuget package for uSync.ContentMappers, it is not clear whether that package is compatible with usync complete or not.  Can you provide some guidance as I need the mappers for NestedContent and DocType Grid Editor.

The same is true for the uSync.HealthCheck Package.

**Comment by KevinJump** [comment]
Hi, 

that content mappers package is for uSync v4. for v8 uSync (and content edition) the mappers are installed as part of the ContentEdtion package.  (its actually the Community.Contrib package - but you don't need to explicitly install it.

Health CHecks are also slightly different, and infact uSync.Complete adds some - for its purposes but there isn't a direct corrolation between the v4 and v8 ones.

**Comment by JohnBergman** [comment]
Thanks Kevin!  You might want to add that to the package notes so others know.  

I dont see the mapper for the doctype grid editor in the config files being lists as a mapper though.

**Comment by KevinJump** [comment]
Hi, will do. 

v8 doesn't list mappers in the say way that v4 does - the mappers are found by the code. so the DocTypeGrid mapper is loaded automatically works without you having to add anything to the files.. you only need to put mappers into the config when they are your own custom editors and you want them to be treated like for example a multinode tree picker.
