### ISSUE TITLE
Troubleshooting - Cannot connect to anothe rsite that is hosted on the same sever.

### ISSUE THREAD

**Issue by JohnBergman** [Jumoo/uSync.Complete.Issues#104]
Using the latest version of usync complete.

I have a server that has 2 umbraco sites hosted (dev and staging).

One each server, in the publish tab, the server shows itself as online, but it cannot connect to the other. Since it is local, there are no firewall's in the way.

Any ideas as to what the issue could be?  Its a blocker for the purchase of the product.

**Comment by KevinJump** [comment]
Hi, 
this setup should work (its how we test it locally all the time) 

What does the connection message say when you click "check access" on the server setup page ?

**Comment by KevinJump** [comment]
https://docs.jumoo.co.uk/uSync/uSync.Complete/getting-started/publisher/addserver/#check-access

**Comment by JohnBergman** [comment]
Interesting, the Server group applied patches overnight, and now this all appears to be working.  Sorry to raise a non-issue.

**Comment by KevinJump** [comment]
no worries
