### ISSUE TITLE
"You licence is NoLicence" message

### ISSUE THREAD

**Issue by AlexandreLocas** [Jumoo/uSync.Complete.Issues#105]
Hi, I am having this message when trying to access uSync Publisher :

![image](https://user-images.githubusercontent.com/29312983/114736109-d0536d80-9d13-11eb-9fee-2586ee5ed93a.png)

I would like to continue evaluation of Publisher (been only 2 days since starting).

 Thank you

**Comment by KevinJump** [comment]
Hi this can happen if the trial licence is created but then an element of it goes missing (e.g there is a bit in the db) - uSync then thinks there is no licence. 

you could try running the licence extender code - this will generate a new 30 day trial licence. 
http://clients.jumoo.co.uk/usync/uSyncCompeteTrialExtender.zip

**Comment by KevinJump** [comment]
i think this can also happen if you ugrade during a trial (because the trial key is version specific) - We will fix that for the next release

**Comment by AlexandreLocas** [comment]
Thank you for the quick answer. The licence extender solution worked.

**Comment by sekmenhuseyin** [comment]
Hi @KevinJump 
I had usync installed, then I've removed it and installed usync.complete
but for now I need to use the trial version until the client buys the licenxe
however I receive this red licence error too and I can not download your extender
this is how my settings look like
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/1363876/09ae0f69-9572-4647-934a-ec5606af20d3)

**Comment by sekmenhuseyin** [comment]
I think because of that I can not use the servers, they all are unavailable

![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/1363876/bd3524b2-088d-4c2a-ae34-27e0d8107956)

**Comment by KevinJump** [comment]
Hi @sekmenhuseyin can you drop us a line info@jumoo.co.uk and we can probably issue you with a temp licence to cover you.
