### ISSUE TITLE
usync8.config Folder Setting outside of IIS web tree

### ISSUE THREAD

**Issue by JohnBergman** [Jumoo/uSync.Complete.Issues#107]
If I set the uSync folder to something like "D:\usync\dev" umbraco fails to load with a boot failure.

The IIS Application Pool account has full access to that folder specifically set (including the d:\usync folder).

I have tried setting it to the following variations:

d:\usync\dev
d:\usync\dev\
d:\\usync\\dev\\

All result in the boot failure.

**Comment by KevinJump** [comment]
Hi,

You need to also add the `AllowUnsafe `attribute to the folder for uSync to allow you to move the folder outside of the web folder (just some more extra protection - to stop accidental config errors)

e.g

```xml
    <Folder AllowUnsafe="True">d:\usync\dev</Folder>
```
