### ISSUE TITLE
Current Server always showing "Local", cannot only pull from "middle" environment regardless of server logged into

### ISSUE THREAD

**Issue by JohnBergman** [Jumoo/uSync.Complete.Issues#110]
The Current Server always indicate"local"

![image](https://user-images.githubusercontent.com/5505858/115589027-3bf18980-a284-11eb-804e-40d1bcbe3814.png)

Preview is setup to push/pull to dev-local and dev-presentation
Presentation is setup to push/pull to dev preview
Dev-Local is setup to push/pull to dev-preview

Local  <= => Preview <= => Presentation

Regardless of which server I am logged into, it still says "local", and I can only pull content from dev-preview when I click the "Sync" button on the ySync Publisher dashboard.

**Comment by KevinJump** [comment]
uSync will calculate which server you are on based on the requesting URL. so If the url underneath "Local" isn't one of the sites you are on, then it won't think you are on dev-preview/stage etc.

so is devwww-preview.startlink.com. another server or should you be accessing the site via the devbackoffice-preview link?

**Comment by JohnBergman** [comment]
each environment as xxxBackoffice.domain.com (and a pair of front end servers).  These were accessed using the devbackoffice.domain.com and devbackoffice-preview.domain.com.  so it should have picked up the domain that matched the url that was entered.
