### ISSUE TITLE
Query about how uSync published scheduling works

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#111]
At the moment we cannot publish any changes as we are getting a warning 
"Publish: 'Error' could not be published because the item is scheduled for release."

This is in the production environment, as a result of editors doing a scheduled 'push' from staging using uSync Publisher.

Am I right that the Scheduling feature of uSync Publisher works as follows:
- updates the destination node(s) but only saves, not publishes
- sets the schedule date for these node(s) using the Umbraco core functionality of scheduled publishing

As if so any problems/queries we have actually relate to core Umbraco scheduling publishing, and nothing specific to uSync? I think that's the case but just wanted to double check. Thank you!

**Version:**
 - Umbraco Version: 8.8
 - uSync Version: 8.8.1
 - uSync.Complete Version: 8.8.1

**Comment by KevinJump** [comment]
Hi, 

yeah schedules are complicated :( - I think you are right if the scheduled dates are sent then uSync is using Umbraco functionality to schedule the publish of the items. if they then can't be published its an Umbraco thing. 

But **there is one Schedule publish fix in uSync v8.8.3 - that might be work updating to** - This fixed an issue where dates where not being removed on a subsequent publish. (https://github.com/KevinJump/uSync8/issues/199)

--- 
In terms of how it works - there is quite a lot to it abd there are two elements as to how uSync handles this. 

1. it imports the schedules against a content item (https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.ContentEdition/Serializers/ContentSerializer.cs#L196) 
2. it then works out if the said item should be published or saved https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.ContentEdition/Serializers/ContentSerializer.cs#L335

If there are issues in uSync with publishing then they will probibly be in the second part when we publish/save or unpublish the content: 

### if the content node has cultures (so it a multi-variant culture).

- loop through all of the cultures that have been filled in the config file. 
  - calculate the state of the culture (e.g should it be published or unpublished based on schedules (if it has any).
     - this is does it have a scheduled date, in the past - then it should be published
     -  does it have one in the future, then it should be saved.
     - does it have an unpublished schedule in the past ? then it should be unpublished. 
  - when we have all of the possible states for the cultures 
   -  publish all cultures with a status of Published 
   - unpublish all cultures with a status of unpublished (https://github.com/KevinJump/uSync8/blob/95742690900e3849bdd041a1dd8f2e6dfd96ab5d/uSync8.ContentEdition/Serializers/ContentSerializer.cs#L442) 


### single culture publish
 - based on the schedule dates 
   -  in the past = publish
   - in the future = save
   - unpublish date in the page = unpublish.

**Comment by LottePitcher** [comment]
Yes, I am just discovering the complexities around scheduled publishing!

This is super useful, thank you very much indeed. And yes, noted about the suggestion to upgrade, sounds good idea.
