### ISSUE TITLE
Exporter: select which dictionary items to include when creating a sync pack

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#112]
When creating a sync pack using Exporter you can select which content items and which media items to include. You can also tick to include dictionary items, which includes all dictionary items without the ability to be selective.

We would like to be able to select certain top level items from the dictionary to include in the sync pack. We would always want to include descendants, but to keep consistent with other selections I guess having a toggle for descendants would make sense.

Would you consider adding this to the road map for Exporter please?

**Comment by KevinJump** [comment]
+1 we will put it on the 'list' 

we probibly didn't add it first time because the generic 'picker' dialog doesn't work for all Umbraco things, but i will check, because we can work around that.

**Comment by LottePitcher** [comment]
Many thanks, as always, @KevinJump !

**Comment by KevinJump** [comment]
Done - will be in the next release _(but we don't have a date for that at the moment)_

**Comment by KevinJump** [comment]
in v8.9.6 😄
