### ISSUE TITLE
Remote Media dashboard - can't see beyond 100 items

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#116]
I believe the uSync 'Remote Media' dashboard is missing paging controls.  We have over 300 images in a folder and we can only see 100 of them.  In both thumbnail view and list view, there are no paging controls at the bottom of the page.

**Version**
 - Umbraco Version: v8.80
 - uSync Version: v8.9.1.0
 - uSync.Complete Version: v8.9.5

**Expected behavior**
When over 100 images in a folder, I expect to see paging controls.

**Comment by LottePitcher** [comment]
PS I am sorry I appear to have a habit of raising issues late on a Friday afternoon...

**Comment by KevinJump** [comment]
We will do this - but its going in the hard pile - for the moment, because paging is difficult, and remote paging between servers is also hard.

**Comment by KevinJump** [comment]
Oh - This was actually in 9.0.4
