### ISSUE TITLE
uSync Complete shows Publish to and Pull content window empty / white with no text and displays no error in logs

### ISSUE THREAD

**Issue by keitharowe** [Jumoo/uSync.Complete.Issues#118]
**Describe the bug**
After upgrade to 8.10.1, the "Publish to..." and "Pull content..." are blank or empty. No errors are shown in console window and no errors in the log. 

**Version:**
 - Umbraco Version:  v8.9.0
 - uSync Version:  v8.9.3
 - uSync.Complete Version: 8.10.1

**To Reproduce**
1. Right click on content node
2. Click on Publish To or Pull content
3. Open blade / window is empty or white (see screenshot)

**Expected behavior**
Expected to see a list of available servers. 

**Screenshots**
![121545669-b911c300-c9d8-11eb-8410-081ed23421a7](https://user-images.githubusercontent.com/14855713/121564846-e0bd5700-c9e9-11eb-8fc6-c98de8bff3bc.jpg)

![Screenshot 2021-06-10 103856 - Settings](https://user-images.githubusercontent.com/14855713/121546048-02621280-c9d9-11eb-9c0c-cdcca8f6049a.jpg)

![Screenshot 2021-06-10 104006 - Push - Pull](https://user-images.githubusercontent.com/14855713/121546103-0beb7a80-c9d9-11eb-922d-2f07958e727a.jpg)

![Screenshot 2021-06-10 104506 - Push - Pull Empty](https://user-images.githubusercontent.com/14855713/121546127-10b02e80-c9d9-11eb-9f25-5f9a2186354d.jpg)

***Other things***
A couple of additional items, Network Mode is set to False as we've been running uSync for a while and have transforms setup. 
I'm seeing the following warning messages under "Health Check"

```
warning:
Found 4 properties with no mappers
The following datatype editors have no known mappers

Umbraco.MarkdownEditor
ArticulateThemePicker
NestingContently
UmbracoForms.FormPicker
Missing mappers might mean that uSync is unable to calulate dependencies for media and documents.

You don't always need mappers (e.g if the property isn't storing links to pages or media) but you might. More info : https://docs.jumoo.co.uk/uSync/v8/developer/mappers/

```

**Comment by KevinJump** [comment]
Hi Keith,

 are there any errors in the browser console ? 

i would suggest you increment the clientDependency "version"  value in your clientdependency.config file - this will ensure that umbraco doesn't return cached files to the browser. 

Kevin

**Comment by KevinJump** [comment]
:( -oh dear - i would have hoped for some errors in the browser 🤔

can you confirm if you do a hard refresh (so with dev tools open Ctrl-Shift-R) - just to double check
also in the network tab  of the browser are there any requests coming back with 500 errors ? 

also you can confirm if the files have been updates (well the new files are there - if while logged in you go to https://yoursite/app_plugins/uSyncPublisher/publish_8100.js) - you should get a single comment from that file to confirm it is in place.

**Comment by KevinJump** [comment]
Just to add  - we could check if the scripts are firing by looking in the network tab.

the first request that fires is a `?action=push` (when you've select push) and this should return the servers:

e.g 

![image](https://user-images.githubusercontent.com/431231/121555834-3d7d3980-ca0b-11eb-9707-b91d597b020f.png)

**Comment by keitharowe** [comment]
Did a hard refresh, can’t hurt 😊

No 500 errors .
I’m not seeing the first request with the querystring ?action=push.

Highlighted request when clicking “Publish to”


***@***.***D75DF2.A4830E00]

Just as an FYI, the “Publish To Server” off the “Save and Publish” yields this:

***@***.***D75DF3.65760B30]

Security / Permissions problem?


-Keith

**Comment by keitharowe** [comment]
Also, this does work too. https://yoursite/app_plugins/uSyncPublisher/publish_8100.js


Yields: // client dependency - cache buster


-Keith

**Comment by KevinJump** [comment]
Hi,think github mangled some of the response images in that post  can you add them to the post via github ?

**Comment by keitharowe** [comment]
For completeness, this shows a missing favicon
![Screenshot 2021-06-10 123217 - 1](https://user-images.githubusercontent.com/14855713/121563332-50324700-c9e8-11eb-8896-67765de5184c.jpg)
When clicking on the "Publish To" off the content node context menu
![Screenshot 2021-06-10 123333 -2](https://user-images.githubusercontent.com/14855713/121563363-57595500-c9e8-11eb-9fa3-c721cca91cec.jpg)

**Comment by keitharowe** [comment]
![image](https://user-images.githubusercontent.com/14855713/121564379-64c30f00-c9e9-11eb-8493-4a7077ee3a5c.png)

**Comment by KevinJump** [comment]
:( - it is behaving like something isn't updated - or is missing, 

When the publisher-dialog loads up it has angular config on it, and then angular should kick off an load the controller. if this was missing or had errors you would see this. in the console. and something should be displayed on the page even if its lots of squiggly brackets e.g `{{` all of this is automatic as part of the platform, if thats not happening i am a bit stumped 

for completeness: my request looks like this. 

![image](https://user-images.githubusercontent.com/431231/121564611-8df89500-ca13-11eb-87f8-a6bbcec1d274.png)

**Comment by keitharowe** [comment]
Ok fair, I’ll go a nuget package reinstall and report back, appreciate the help thus far.


-Keith

**Comment by keitharowe** [comment]
There was a web application firewall blocking traffic to the uSync URL. Thank you very much for helping me troubleshoot the problem. I appreciate it.
