### ISSUE TITLE
Syncing List View Child Items does not delete them

### ISSUE THREAD

**Issue by KamenovBoris** [Jumoo/uSync.Complete.Issues#121]
When trying to push content from one server to another child list items are not deleted.
I am testing with 2 environments that both have a list view item named FAQ  and children items inside this list.

    Initiate push on a document type that has active List View and children
    Make sure that on the environment side there is one more child list item that should be deleted on sync
    Push the changes (Deletion is shown)
    However the child item that should have been deleted is still there

Screenshots:
![Step1](https://user-images.githubusercontent.com/7759990/123743448-f077df00-d8b5-11eb-9ed9-d1006845f64c.png)
![Step2](https://user-images.githubusercontent.com/7759990/123743453-f241a280-d8b5-11eb-9da8-501f19a49270.png)
![Step3](https://user-images.githubusercontent.com/7759990/123743460-f4a3fc80-d8b5-11eb-8ee6-237fee076038.png)
![Step4](https://user-images.githubusercontent.com/7759990/123743471-f66dc000-d8b5-11eb-8134-8cb78064a2ed.png)

Expected behavior
The child item gets deleted on sync.

Version: uSync 8
v8.9.1.0 +
Content Edition (v8.9.1.0), Snapshots (v8.9.4.0), Exporter (v8.9.4.0), PeopleEdition (v8.9.4.0), Publisher (v8.9.4.0), Complete (v8.9.4.0)

Thanks

**Comment by KevinJump** [comment]
Hi, 

yep i can reproduce this, just looking into the fix for it now. 

Kevin

**Comment by KamenovBoris** [comment]
Hi,
Any chance this is will be fixed and released soon. I want to inform a client when they will be able to use it since it is something that is blocking them at the moment.
Best Regards,
Boris

**Comment by KevinJump** [comment]
Hi, we are just testing the release this morning. (upgrades/fresh installs etc) - all going well should be today (5th July)

**Comment by KevinJump** [comment]
Out Now !  

https://github.com/Jumoo/uSync.Complete.Issues/releases/tag/8.10.2
