### ISSUE TITLE
Azure Media files not syncing

### ISSUE THREAD

**Issue by Helza** [Jumoo/uSync.Complete.Issues#122]
**Describe the bug**

Publishing a content item does not seem to copy over the media file itself.
The Media item is created within the media library, however the actual image content is missing.

The different environments do use different Azure Connection Strings

**Version (please complete the following information):**
 - Umbraco Version: 8.13.0
 - uSync Version: 8.9.3
 - uSync.Complete Version: 8.10.1

![file_origin](https://user-images.githubusercontent.com/5858777/123787818-8ffb9880-d8db-11eb-8628-06b54271550a.PNG)
![file_target](https://user-images.githubusercontent.com/5858777/123787822-912cc580-d8db-11eb-9814-10d2d220948c.PNG)

**web.config Development:**
![file_dev](https://user-images.githubusercontent.com/5858777/123788457-52e3d600-d8dc-11eb-8d1a-637cec46055b.PNG)

**web.config Staging:**
![file_webconfig](https://user-images.githubusercontent.com/5858777/123787849-97bb3d00-d8db-11eb-8303-e3eaeb6c494f.PNG)

**security.config Development**
![file_security-dev](https://user-images.githubusercontent.com/5858777/123788458-537c6c80-d8dc-11eb-8004-5f6831c8581b.PNG)

**security.config Staging**
![file_staging](https://user-images.githubusercontent.com/5858777/123787850-9853d380-d8db-11eb-871b-f2cc734c079b.PNG)

**Comment by KevinJump** [comment]
Hi,

There are some oddities around having the media folder not called media but starting media (see https://github.com/Jumoo/uSync.Complete.Issues/issues/63) - It might not be this - but might be worth a check.

 i will take a look and see if i can recreate with a setup like you have.  and confirm if i can recreate this.

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
