### ISSUE TITLE
Unpublish not unpublishing on target

### ISSUE THREAD

**Issue by IRooc** [Jumoo/uSync.Complete.Issues#125]
**Describe the bug**
We have two servers, staging and production. Publishing items on staging and publish to server production works fine. But when we unpublish on staging and call "publish to production". The dialog mentions that the Published boolean will be set to false (for the default culture) but on the target (production) the changelog is "Save" and "Publish" instead of unpublish.

Staging log:
![image](https://user-images.githubusercontent.com/5981147/127134252-24255c6e-bca9-4c99-8afa-63e7714d0383.png)

Production log:
![image](https://user-images.githubusercontent.com/5981147/127134208-b5f28d04-5478-4425-b56d-54fe457f60ce.png)

**Version (please complete the following information):**
 - Umbraco Version: 8.15
 - uSync Version: v8.9.3 + Content Edition (v8.9.3), Snapshots (v8.10.1), Exporter (v8.10.1), PeopleEdition (v8.10.1), Publisher (v8.10.1), Complete (v8.10.1)

**To Reproduce**
We have a 'vary by culture' doctype setup but currently only with 1 default culture en-GB
1. Go to staging server create content for default language
2. Click on publish to to deploy this change to production
3. On staging click 'unpublish' to unpublish the item
4. On staging click on publish to to deploy this change to production
5. On production the item is still published

**Expected behavior**
The item is also unpublished on production

**Screenshots**
Change log on staging before publish
![image](https://user-images.githubusercontent.com/5981147/127135210-33d72b54-2978-4ddf-93ca-da11192cead9.png)

Report on staging after publish
![image](https://user-images.githubusercontent.com/5981147/127135389-a318afe9-dda2-416a-b5c6-d2ab318590e4.png)

**Comment by KevinJump** [comment]
Looking into this now.

**Comment by IRooc** [comment]
Just did a PULL from staging to our local dev environment and it pulled the drafts but published the item as well.

**Comment by KevinJump** [comment]
Looks like its a Umbraco version thing :( - works on our base install (which is quite old v8.1) - on fresh v8.15 we do see thls issue) 

having a look to see if we can find out why.

**Comment by patrickdemooij9** [comment]
I wonder if it might be related to this issue: https://github.com/umbraco/Umbraco-CMS/issues/10695

**Comment by KevinJump** [comment]
yes - Looks something like that  :( 

line : [106 of the content serializer](https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.ContentEdition/Serializers/ContentSerializer.cs#L106)

               published.Add(new XElement("Published", item.IsCulturePublished(culture),
                        new XAttribute("Culture", culture)));

is returning true and false on the same site depending on how its called 😕 

![image](https://user-images.githubusercontent.com/431231/127151178-4b6c8bdb-5b52-4d77-a19e-a8c91d6cf78e.png)

Will see if i can identify why - and report into issue if its the same thing

**Comment by KevinJump** [comment]
I think its not the same issue, but it is detestably a umbraco bug. 

if you have a variant with a single culture and you unpublish the single culture. then the publishedCultures value of the content item still contains the culture although the overall item.published value = false. 

I am guessing when you completly unpublish an item by unpublishing all its languages - that doesn't wipe the publishedCultures value but it does set the master unpublished value. 

we can work around this in uSync. and if i can work out where this happens in Umbraco.Core i will log an issue on the main repo.  because i think this is confusing.

**Comment by KevinJump** [comment]
Workaround for this issue, in uSync - will be part of next uSync release.
