### ISSUE TITLE
Cannot push custom content types

### ISSUE THREAD

**Issue by benjaminc** [Jumoo/uSync.Complete.Issues#128]
**Describe the bug**
I have custom data in my database, that is represented in custom sections in the back-office.  I'm trying to add uSync Publisher right-click menus to those sections to transfer my data between servers.  When I call `uSyncPublishDialogManager.openSyncDialog` with the `options.contentType` set to my custom type, I get an error about the object returned by the `getItemById` method not have a `then` method on it.

**Version (please complete the following information):**
 - Umbraco Version: 8.15.1
 - uSync Version: 8.9.7
 - uSync.Complete Version: 8.10.3

**Cause**
The problem lies in the `App_Plugins/uSyncPublisher/components/uSyncPublishingActionComponent.js` script in the `getItemById` method.  If the content type is not one of the known types, it just returns the item passed in.  The problem is that all the other return statements are returning a `Promise` object, and the caller expects a `Promise` object to be returned.  I believe the fallback return statement should be changed from `return item;` to `return new Promise(resolve => resolve(item));`

**Comment by KevinJump** [comment]
Hi, 

we've fixed that for the next release (and we will push it to our nightly feed).

But it would be really good to have a chat with you about how it might work for you. 

we are in the middle of looking at how to make the whole menu area more customizable, so we can add menus to all items (like doctypes, data types, and forms) - so we are tring to make more of the dialog logic generic. 

I think we could make the whole process eaiser for you along the way (i suspect there will be other blockage in the dialogs). 

if you want to drop me an email kevin@jumoo.co.uk we could have a chat ?

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
