### ISSUE TITLE
Old typo in en-US localization file

### ISSUE THREAD

**Issue by leekelleher** [Jumoo/uSync.Complete.Issues#130]
**Describe the bug**

Installed uSync Complete (Umbraco package, via CMS backoffice). I'd already had uSync v8.9.7 installed previously, and I noticed an old typo appear in the localized values of the "en-US.xml" file in my local Git repo.

    <key alias="loadbalancedWarning"><![CDATA[Umbraco appears to be running in a load balanced envrionment. <a href="https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/#faqs" target="_blank">You should not load balanace the umbraco back office</a>. We strongly recommend you do not run uSync from a load balanced back office.]]></key>

Specifically, `envrionment` and `balanace` - that I'd previously fixed in https://github.com/KevinJump/uSync/pull/222

I'm thinking that uSync Complete isn't using the updated localization file? 🤔 

---

**Version (please complete the following information):**
 - Umbraco Version: **v8.16.0**
 - uSync Version **v8.9.7**
 - uSync.Complete Version **v8.10.3**

**To Reproduce**

1. On a site that already has uSync (regular) installed, check the `loadbalancedWarning` value in the en-US.xml localization file, make sure the typo is corrected.
2. Install uSync Complete on the same instance.
3. Check the `loadbalancedWarning` value (in en-US.xml), it will now have the typo.

**Expected behaviour**

I expect the old typo to not be there. Shazam! ⚡  _(Sometimes these comments sound condescending, not my intention 😻)_

**Comment by KevinJump** [comment]
i will have to check - guessing the uSync version is still the problem as the file comes from there - i've probably regressed somewhere 😄

**Comment by KevinJump** [comment]
Just to confirm are you installing the package file (zip) 🤯

**Comment by leekelleher** [comment]
> Just to confirm are you installing the package file (zip) 🤯

I know right?! Contrary to popular belief, some of us still use the backoffice to install packages! 🤷‍♂️ 

NuGet just doesn't fit into my workflow with using ASP.NET Websites (e.g. App_Code, as opposed to Web Apps).

**Comment by KevinJump** [comment]
Yep - for some reason the file is out of date in the package, i am guessing my build script is picking up an old file from somewhere. we are super close to a new release so this can be snuck in for the "legacy" package user(s?)

**Comment by leekelleher** [comment]
Cool.  Also to note, I'm missing the "/App_Plugins/uSyncHistory/history.html" file from the Umb package version too. Should I raise that as a separate issue?

**Comment by KevinJump** [comment]
yes that's fixed that for the next uSync package release too.
