### ISSUE TITLE
v9: System.IO.DirectoryNotFoundException while adding license

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#132]
**Describe the bug**
Even though I don't have a license for v9 yet, I noticed that it tries to write licenses to the ~/config directory. This directory doesn't exist anymore on U9. Either the directory should be created, or another path should be used.

**Version (please complete the following information):**
 - Umbraco Version: 9 rc 2
 - uSync Version 9 rc 2
 - uSync.Complete Version 9 beta 5

**Comment by KevinJump** [comment]
I have checked wit the core team and for v9 - The Umbraco recommendation is to put this file in `/umbraco/Licenses`  - so that is where we have moved it to.
