### ISSUE TITLE
Add ability to push/pull individual Scripts and CSS separately from Templates

### ISSUE THREAD

**Issue by ewilkinson-marathon** [Jumoo/uSync.Complete.Issues#136]
**Is your feature request related to a problem? Please describe.**
The client's deployed an update to the frontend Bootstrap framework of their site, and they wanted to be able to select the relevant changes to Templates, Scripts, and CSS individually and then push them to the higher environment. Currently if Templates are included, it seems all Scripts/CSS are sent - but they needed to only send the relevant updates, not all. The client is requesting this capability to push/pull individual Stylesheets and Scripts for use on similar future development tasks.

**Describe the solution you'd like**
Right click on the script or stylesheet in the Settings > Scripts, or Settings > Stylesheets section, and receive an option to Push To.. or Pull From.. one of the other servers.

**Describe alternatives you've considered**
With the recent release of the ability to specify more item types in their context menu actions, such as Templates - we're hoping to have the same feature to push/pull individual Scripts and Stylesheets by right-clicking.

**Comment by KevinJump** [comment]
Hi, 

We will look into this, but actually the way files work inside uSync is a little bit diffrent - so it will take a bit of doing to break the files down into individual items, 

(File moving is done by folder and hashes of the folders are sent between servers, before individual changes are sent across)

It might therefore take us a little bit of work to be able to break files down like this, but we will certainly take a look.

**Comment by KevinJump** [comment]
Hi, Just tidying up. this feature has been implemented, and there was a fix for the single template issue also included in 8.11.7 #154
