### ISSUE TITLE
Better readability of changes when pushing/pulling content

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#144]
**Is your feature request related to a problem? Please describe.**
Right now, the only visual indication is a green or red color. When you're having a large amount of content, and your changes are only minimal, such as some comma's and dots, it's really hard to spot the changes.

**Describe the solution you'd like**
I think it would be extremely useful to also change the background of the changed characters, such as on GitHub:
![image](https://user-images.githubusercontent.com/7643972/142654109-9e582aa1-9c46-4975-a443-e9bb78c44803.png)
Or another example when you search on a page in Firefox and use the "Highlight All" option:
![image](https://user-images.githubusercontent.com/7643972/142654307-798b53f1-9426-470c-a1b3-386ef2cbc0f3.png)

That way it's much more obvious than a small difference in color.

**uSync v9.**

**Comment by KevinJump** [comment]
yeah - i think we are using the same styles as Umbraco does in the rollback UI, but i am sure we can make it clearer.

**Comment by KevinJump** [comment]
will be fixed in next uSync 9.x release.
