### ISSUE TITLE
The method openSettingsPush on the angular service uSyncPublishDialogManager could not be found

### ISSUE THREAD

**Issue by lbras** [Jumoo/uSync.Complete.Issues#149]
I set up a barebones Umbraco install to try the latest uSync 8.x version. I get the following error on the browser console when clicking on a server's `Sync Settings` menu button:

`The method openSettingsPush on the angular service uSyncPublishDialogManager could not be found`

My `\App_Plugins\uSyncPublisher\resources\uSyncPublishDialogManager.js` doesn't have an `openSettingsPush` method, but the previous version (from source control) had.

**Version:**
 - Umbraco Version: v8.17.1
 - uSync Version: v8.10.6
 - uSync.Complete Version: 8.11.5

**To Reproduce**
1. Go to Settings and expand uSync Publisher
2. Right-click on a server to show the context menu
3. Click `Sync Settings`
4. See error in browser console

**Screenshots**
![image](https://user-images.githubusercontent.com/4013113/144902266-1157e55d-62d1-4812-8dc2-c7fee70a358e.png)

**Comment by KevinJump** [comment]
thanks, we have fixed this for the next release, along with adding a distinction between push and pull 

![image](https://user-images.githubusercontent.com/431231/145023101-20f22171-baee-44c4-aa78-25af6b67886b.png)

For now these menu options mimic the option at the top right of the server config page - which is the thing we did update in a previous release but forgot to also change refrences in this menu. 

![image](https://user-images.githubusercontent.com/431231/145023235-a9676ebe-3bc1-494f-931a-1f2c154ac26e.png)
