### ISSUE TITLE
Umbraco Forms syncing

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#150]
**Is your feature request related to a problem? Please describe.**
Yes, uSync doesn't sync Umbraco Forms. No options are given for Forms. Also forms that are included through Macro aren't synced.

**Describe the solution you'd like**
Add the ability to synchronize forms. 

**Describe alternatives you've considered**
Not available, only manual synching.

**Additional context**
None that I can think of.

**Comment by KevinJump** [comment]
Hi,

Do you have the latest version of the uSync Forms package installed alongside uSync.Compltete ? that offers the ability to sync the forms. 

it might not sync forms included in macros but i will check that.

**Comment by Nuklon** [comment]
No, I have not, I thought everything was included in the complete package (hence the name _complete_). I have added this package and I now get these options.

**Comment by KevinJump** [comment]
Hi yeah i get that but with forms is a bit of a chicken and egg thing, we can't install the code to sync forms without Forms being installed, or it breaks as we cant find the dependencies. so we can't package it in complete, has to be install forms then uSync.forms 😞

**Comment by Nuklon** [comment]
Interesting, thanks. I will include Forms package then.
