### ISSUE TITLE
"ITemplate Update" always detects entire file as deleted

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#151]
**Describe the bug**
Whenever I change a **Content** item, the referenced ITemplate always gets detected as completely deleted.

![image](https://user-images.githubusercontent.com/23340481/145401156-786b2508-2137-42f4-85f9-82bef1088ada.png)
This is just one example, when I select the root node then all used ITemplate get detected as complete deleted.

**Version (please complete the following information):**
 - Umbraco Version: 9.1.2
 - uSync Version: 9.0.4.
 - uSync.Complete Version: 9.0.4
 - .NET: 6.0

**To Reproduce**
1. Have two instances, local and remote.
2. Make a 1:1 copy from local to remote (DB and all)
3. Make some changes locally to some document.
4. Push this node to remote.
5. See that ITemplate is detected as fully deleted.

If I push this though, nothing breaks. The site keeps running correctly with the changes.

**Comment by KevinJump** [comment]
Hi 

Thansk, we can reproduce this now, and i think we have a fix - just doing some testing.
