### ISSUE TITLE
Content changes should include URL to see which item changed

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#152]
**Is your feature request related to a problem? Please describe.**
When you publish the root item to remote there's no way to see which item changed when multiple items have the same name.

**Describe the solution you'd like**
Maybe this can be added below the name or in Details.

**Comment by KevinJump** [comment]
👍  - Good idea we will see what we can do in the UI

**Comment by KevinJump** [comment]
paths included in report in core (next v9 release) 76c84925874ee9edb977bbf90cc9c3e43da08123

**Comment by KevinJump** [comment]
This will trickle through to complete because we share views. for reporting etc.
