### ISSUE TITLE
Child of node not deleted after publishing to Umbraco instance.

### ISSUE THREAD

**Issue by philipullersted** [Jumoo/uSync.Complete.Issues#163]
**Describe the bug**
When I delete a child of a node on one Umbraco instance and Publish it to another Umbraco instance, the child is not deleted on the other Umbraco instance.

**Setup**
I have setup 2 Umbraco projects from scratch, that I have used to test this.
They are setup with the following.
 - Umbraco Version: 9.2.0
 - uSync Version 9.0.6
 - uSync.Complete Version 9.0.6
 - An empty Document from the "Document Type with Template"
 - The appsettings.json file shown further down
 - The content shown in the first picture. They are both using the empty document.

**To Reproduce**
1. Setup 2 Umbraco instances with their own database
2. Ensure the content of the 2 Umbraco instances are in sync
3. Delete the child of a node in Umbraco instance 1
4. Publish to Umbraco instance 2, via the "Publish to" option

**Expected behavior**
The child that was deleted in Umbraco instance 1, should now also be deleted in Umbraco instance 2.

**Logs**
[13:33:32 INF] Adding examine event handlers for 3 index providers.
[13:33:32 INF] Document Root (id=1065) cultures: en-us have been published.
[13:33:32 WRN] No handler was found for ContentHandler item might not process correctly

**Appsettings.json**
```
"uSync": {
    "Settings": {
      "RootFolder": "uSync/v9/",
      "DefaultSet": "Default",
      "ImportAtStartup": "None",
      "ExportAtStartup": "None",
      "ExportOnSave": "None",
      "UiEnabledGroups": "All",
      "ReportDebug": false,
      "AddOnPing": true,
      "FailOnMissingParent": false,
      "CacheFolderKeys": true,
      "ShowVersionCheckWarning": true,
      "CustomMappings": {},
      "EnableHistory": true
    },
    "Sets": {
      "Default": {
        "Enabled": true,
        "HandlerGroups": [],
        "DisabledHandlers": [],
        "HandlerDefaults": {
          "Enabled": true,
          "Actions": ["All"],
          "UseFlatStructure": true,
          "GuidNames": false,
          "FailOnMissingParent": false
        },
        "Handlers": {
          "ContentHandler": {
            "Enabled": true
          },
          "PublishedContentHandler": {
            "Enabled": true
          }
        }
      }
    },
    "Publisher": {
      "Settings": {
        "IncomingEnabled": true,
        "AppId": "75d816c2-390a-45c9-bd37-66c01a90b6c6",
        "AppKey": "+Hi+VGo1CHcjwsXuCoZ5uiw1ELzPFi1ytAJR6ggXguY="
      }
    }
  }
  ```
  

**Screenshots**
![image](https://user-images.githubusercontent.com/89908193/152155088-797d1099-73f0-44f1-8e0b-01a85ff1881f.png)
Content setup
![image](https://user-images.githubusercontent.com/89908193/152155024-45540f6f-ba73-4f9c-8c3a-830426f820bc.png)
Result of Publishing a deleted child of a node to another instace of Umbraco(Where the child exists).

I have noticed that it says "No handler was found for ContentHandler item might not process correctly", but the ContentHandler should be enabled, since I enabled it via the appsettings.json

When I view the appsettings.json from the uSync -> Settings, I also see that DisabledHandlers is filled with the following,  even though I have specified that it should be empty.
```
"DisabledHandlers": [
                    "PublishedContentHandler",
                    "MediaFileHandler",
                    "PartialFileHandler",
                    "PartialMacroFileHandler",
                    "ScriptFileHandler",
                    "StyleSheetHandler"
                ]
 ```
Could that be the cause? And if so, how do I go about fixing it?

**Comment by KevinJump** [comment]
Hi, 

We've found and fixed this one now. 

we have a nightly build if you want to try it - but if you want to wait a proper release is due out next week and will include this fix. 

https://dev.azure.com/jumoo/Public/_packaging?_a=package&feed=nightly&package=uSync.Complete&protocolType=NuGet&version=8.11.8-rc001.20220203.4&view=overview

**Comment by MaccabiWeb** [comment]
Hi Kevin,
Hope this is the right place for this...
Wee have a similar issue with v9.4.0 + Snapshots (v9.4.0), Exporter (v9.4.0), PeopleEdition (v9.4.0), Publisher (v9.4.0), Complete (v9.4.0).
We see the child node to be deleted in report, and then as done but node is not deleted (node was published to other instance using Publisher before).
Thanx
koshet
