### ISSUE TITLE
"Settings" Full Sync breaks document type inheritance/nesting

### ISSUE THREAD

**Issue by wadrschall** [Jumoo/uSync.Complete.Issues#169]
When using the "Everything" Full Import, all doctype inheritance/nesting works. Running a standard "Settings" import doesn't have any pending changes, so nothing updates. Running a "Settings" Full Import however breaks the nested inheritance for a variety of doctypes. According to the import log, this import is removing the Allowed Doc Types. If I then run an "Everything" Full Import again, the log indicates those doctypes have the Allowed Types added back in and the nested inheritance again begins to work.

This is using uSync 9.2

**Comment by KevinJump** [comment]
HI, 

This is fixed over on the main uSync branch now. 

i think the allowed thing is a red herring 'Allowed' doctypes is actually the structure (what you see under permissions. The actual issue was the parent item was being removed and then re-added on subsequent syncs.
