### ISSUE TITLE
Adding compositions to nested doctypes breaks usync Full "Everything" and "Settings" syncs.

### ISSUE THREAD

**Issue by wadrschall** [Jumoo/uSync.Complete.Issues#170]
When utilizing nested/inherited document types, umbraco allows an administrator to add additional compositions to individual document types (on top of the composition added via inheritance). However, after running either "Settings" or "Everything" full syncs result in the Document Types view under "Settings" to show documents out of their nested positions. The usync logs indicate the "Allowed" types are removed when the composition is in place.

This is using uSync 9.2

**Comment by KevinJump** [comment]
Hi, 

I think this is the same issue as #169 - so should be fixed in the next release of uSync. [#372](https://github.com/KevinJump/uSync/issues/372)
