### ISSUE TITLE
Improved file count

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#183]
**Is your feature request related to a problem? Please describe.**
uSync always seems to report 1/1 items under File changes (with the name "Files"). See below:
![image](https://user-images.githubusercontent.com/7643972/178033043-6446a5ae-0dd2-4447-a9ed-2c698a1ef78d.png)

When you click on Details, there are actually a lot more files available, see below:
![image](https://user-images.githubusercontent.com/7643972/178033132-2f60acd5-65a8-440a-a485-5fd71bffafd2.png)

**Describe the solution you'd like**
I think this count can be improved by actually counting the changes contained within this. It's a bit odd that it's only containing "Files" as an item.

**Comment by KevinJump** [comment]
Yeah - we actually have two ways of transferring files inside uSync.Complete now, we need to port this process to the 'new' way because it gives better reporting and counts etc.

**Comment by KevinJump** [comment]
File count changes Done and will be in 10.1.0 
+ also will now only report _ViewImports.cshtml as changing if its difftrent after we have renamed the site usings in the file.
