### ISSUE TITLE
Synchronization issues

### ISSUE THREAD

**Issue by bielu** [Jumoo/uSync.Complete.Issues#191]
Hi Kevin!
I am testing usync complete for one of clients and we hit big issue which is blocker for use to continue usage.
**Describe the bug**
I tried to sync site between evironments and noticed instead of getting 1 item I am getting all 800 
**Version (please complete the following information):**
 - Umbraco Version: 8.15.1
 - uSync Version 8.11.3
 - uSync.Complete Version 8.11.10

**To Reproduce**
1. Go to content 
2. click any node in tree
3. click publish to
4. choose server
5. deselect children, dependencies, media
6. click publish
7. wait for report

**Expected behavior**
Only selected node is send to new environment

**Actual behavior**
Whole site is synchronized
**Screenshots**

**Comment by KevinJump** [comment]
Hi, 

Can you check the advanced server settings and see if include ancestors or include linked items is ticked ?

if include linked items is ticked, then you might well end up with the entire site being found by the dependency check and sending it all across . 

its very unlikely that you need Include Linked items checked - so if it is uncheck that one.

**Comment by bielu** [comment]
@KevinJump it was clicked, test it now! Thanks

**Comment by KevinJump** [comment]
yeah in v9/10/11 its properly hidden and always off - because its a pain.

**Comment by bielu** [comment]
@KevinJump worked. Closing :)
