### ISSUE TITLE
Diffrent

### ISSUE THREAD

**Issue by garpunkal** [Jumoo/uSync.Complete.Issues#195]
**Describe the bug**
"Diffrent" Spelling mistake on "Remote Content" tab 

**Version (please complete the following information):**
Umbraco version 10.4.0
v10.3.3 + Snapshots (v10.4.1), Exporter (v10.4.1), PeopleEdition (v10.4.1), Publisher (v10.4.1), Complete (v10.4.1)

**To Reproduce**
Click on the Content section, choose a server, and check in sync status. 
If status is different, it shows a label that's spelt incorrectly. "Diffrent"

**Expected behavior**
Spelt correctly "Diffrent" => "Different"

**Screenshots**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/13114807/225053314-af9404ff-98f2-4a07-8d14-cda5db2148f6.png">

**Comment by KevinJump** [comment]
thanks, turns out we've done that in 4 different places.

Fixed for the next v10/11 releases.

**Comment by KevinJump** [comment]
Fixed in v11.1
