### ISSUE TITLE
Invalid license for Agency license

### ISSUE THREAD

**Issue by bielu** [Jumoo/uSync.Complete.Issues#196]
**Describe the bug**
Hi Kevin, I tried to active our company agency(Etch UK) license and hit issue with it showing invalid lincense.
What I tried:
- put primary domain with license
- put direct domain with license
both finished with same result.

**Version (please complete the following information):**
 - Umbraco Version: 8.18.5
 - uSync Version [e.g. v8.4.3]
 - uSync.Complete Version [e.g v8.9.1]

**To Reproduce**
1. Go to license settings of usync complete
2. Insert license details
3. Save

**Expected behavior**
License should activate without showing information about invalid license

**Screenshots**
I can provide screenshot if required

**Comment by KevinJump** [comment]
Hi,


For your agency licence it's your 'agency' domain, not actually the domain that the site is - (so thats etchuk.com for you)

feel free to drop me an email kevin@jumoo.co.uk - if you want to send anything over.

**Comment by bielu** [comment]
@KevinJump Yeah i tried etchuk.com it didnt work :), I will send you mail after I will finish one bit on the solution

**Comment by KevinJump** [comment]
Hi, drop me an email with screenshots. i 'll take a look (also check you are using the v8 key)

**Comment by bielu** [comment]
Resolved, wrong key used.
