### ISSUE TITLE
Exporter sync pack filename uses 12hr time

### ISSUE THREAD

**Issue by ianleeder** [Jumoo/uSync.Complete.Issues#201]
**Describe the bug**
Exporter sync pack filenames use 12hr time.  Apart from being misleading, this could introduce filename conflicts.

**Version (please complete the following information):**
- Umbraco version 10.5.1
- uSync version: v10.3.3 + Snapshots (v10.4.1), Exporter (v10.4.1), PeopleEdition (v10.4.1), Publisher (v10.4.1), Complete (v10.4.1)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'uSync'
3. Click on 'Exporter'
4. Select content to include.
5. Click 'Create' button

**Expected behavior**
The default suggested filename for a syncpack contains the local date/time.  It should use 24-hour time, but it uses 12-hour time.

**Screenshots**
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/8241300/066e92f8-1e91-4b45-8654-5c18c47bd994)

![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/8241300/cf653762-bdaa-46b5-a7f5-359fe55ffbff)

**Comment by KevinJump** [comment]
Fixed for next release.
