### ISSUE TITLE
Can't exclude content by type

### ISSUE THREAD

**Issue by ttdac** [Jumoo/uSync.Complete.Issues#203]
**Describe the bug**
I need to exclude content data type from sync and can't make it work. I already tried `Exclude` and `ExcludeContentTypes` options from `appsettings.json`.

**Version (please complete the following information):**
 - Umbraco Version: 11.4.0
 - uSync Version: I have only installed uSync.Complete.
 - uSync.Complete Version: 11.2.0

**To Reproduce**
I only need to use Snapshots and Publisher. 
``` javascript
  "uSync": {
    "Settings": {
      "ExportOnSave": "None",
      "DisableDashboard": true
    },
    "Sets": {
      "Default": {
        "DisabledHandlers": [ "DomainHandler" ],
        "Handlers": {
          "PublishedContentHandler": {
            "Settings": {
              "Exclude": "Brand 1/Settings/Site Configuration", // I tried both options
              "ExcludeContentTypes": "siteConfig" // I tried both options
            }
          }
        }
      }
    },
    "Publisher": {
      "Settings": {
        "IncomingEnabled": true,
        "OutgoingEnabled": false,
        "AppId": "MY_APP_ID",
        "AppKey": "MY_APP_KEY"
      }
    }
  }
```
- source usync settings:
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/136341712/11010861-8f32-4d65-b97d-c1441fe6f419)
- content node I want to exclude:
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/136341712/fb289d19-0e34-402a-8155-6197a67ba77b)
- content doc type:
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/136341712/7c7411d2-cb47-47cb-a425-85d96e7f4c24)

**Expected behavior**
Exclude the content doc type `siteConfig` I'm using on this project from sync.

**Comment by KevinJump** [comment]
Hi, 

The Publisher stuff, is in a slightly different location.  `uSync:Publisher:Handlers`. 

*Its also worth noting that while all these settings are theoretically possible, its not something we fully support, in general it should work, but you might find that you get false positives in that usync reports changes that are not changes because things are missing.*

> Note we have extra DisabledHandlers because internally uSync will add the content handlers to disabled, but once you choose to set the list of disabled handlers, uSync will no longer do that, and if you don't disable the content one then for content saved values will be pushed and published, vs the Published values which is the default value.

```json
"uSync": {
    "Publisher": {
      "Handlers": {
        "DisabledHandlers": [ "ContentHandler", "ContentTemplateHandler", "DomainHandler" ],
        "Handlers": {
          "PublishedContentHandler": {
            "Settings": {
              "RulesOnExport": true,
              "Exclude": "Path/To/Exclude",
              "ExcludeContentTypes": "siteConfig"
            }
          }
        }
      }
    }
  }
```

**Comment by ttdac** [comment]
Many thanks, it is working now! FYI I couldn't find these options on the docs.
