### ISSUE TITLE
Cannot get out of details view when x frame options are set

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#207]
**Version (please complete the following information):**
 - Umbraco Version: 12.2
 - uSync.Complete Version: 12.2

**To Reproduce**
1. Have a destination site with “X-Frame-Options“ directive set to “sameorigin“.
2. Publish content (a page) from a source to this destination.
3. Click on Content > Details.
4. In console this is printed: "The loading of “https://site/” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“."
5. Now you get a blank screen you cannot get out of. Refreshing page works of course but then you need to restart the push.

**Expected behavior**
It should detect this and continue loading the "Detail" view as before.

**Screenshots**
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/7643972/1b02f569-4a99-4c66-8638-0c77f3f2d9b3)

**Comment by KevinJump** [comment]
This is fixed for the next release - v12.2.1 (Eta very soon)

**Comment by PhyxionNL** [comment]
Thanks, can confirm, works correctly now 👍

**Comment by KevinJump** [comment]
Yeah - I looked at this the other day and it was already fixed - so the other things i did to the details view must have done it.
