### ISSUE TITLE
Child nodes being created in Recycle Bin

### ISSUE THREAD

**Issue by poornimanayar** [Jumoo/uSync.Complete.Issues#21]
I set up a doctype collection - Blog Landing Page and Blog Page on my master and receiver site. I published the blog landing page which published smoothly on to receiver site. Then I deleted the blog landing page on the receiver site to see whether I can publish child items alone. Then I tried to publish a blog page from my master to receiver. It failed but I could see the page was on the receiver as a child page to the deleted blog landing page. I expected it not to fail and created beneath the site "Home" page. Now I emptied my recycle bin and the tried publishing a blog page from master to receiver. This time blog page was added as a child to site root

Attached gif :-)
![usync](https://user-images.githubusercontent.com/3941753/76227970-fd337800-6217-11ea-8141-c85041cf0943.gif)

**Comment by KevinJump** [comment]
yeah - We have been thinking about what to do with orphaned pages. Still not 100% sure 😕 

I "think" its probably more intuitive to always fail if the parent isn't in the target site? - that way you know what is happening ? 

The current behavior of publishing to the root, could potentially cause issues, (and publishing to the recycle bin too!). 

At the moment If you have include ancestors always on then you can avoid this as any parent pages will also be pushed,

 but i can see that isn't ideal as you might not want those pages pushed at the same time, so I think we need some form of 'check parent' option that you can have, to enforce some form of sanity to what happens.

**Comment by poornimanayar** [comment]
Makes sense Kevin. It was only a test scenario TBH. And I am still trying to come up with best solution for us.

**Comment by KevinJump** [comment]
yeah, i think we are still seeing how people use it, and tweaking defaults and options, but this is something we are going to see if we can make better. :)

**Comment by poornimanayar** [comment]
No rush Kevin, I spotted this so thought of logging it.

**Comment by KevinJump** [comment]
The 'Missing Parent' setting in uSync 8.6 ([see notes](https://github.com/KevinJump/uSync8/releases/tag/v8.6.0)) (and hence uSync.Complete) is an attempt to address this, essencially you will now get warned about orphaned pages, and in the default setup complete will actually fail those pages _(although you can set it - so they still get imported in the nearest possible location)._
