### ISSUE TITLE
uSync 13 not syncing media properly

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#212]
**Describe the bug**

**Version (please complete the following information):**
 - Umbraco Version: 13 RC3
 - uSync.Complete Version: 13 RC2

**To Reproduce**
Fails both ways (pull and push).
1. Add new media, e.g., an image.
2. Create new content node and refer to that image.
3. Push the content node to other server.
4. The media isn't included, despite enabling "Include media".

What works:
First push media folder, then push content.

**Comment by KevinJump** [comment]
Fixed in uSync.Complete v13.0-rc3

https://www.nuget.org/packages/uSync.Complete/13.0.0-rc3
