### ISSUE TITLE
Publish all the things rendered over servers

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#213]
**Describe the bug**
Issue has existed for quite some time, thought I'd report it now. See:
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/23340481/5777cbf1-35b9-40f0-8afd-d9b2e69f4dc9)

Using Firefox.

**Comment by KevinJump** [comment]
Fixed in uSync.Complete v13 rc3 (and we will backport this too).

https://www.nuget.org/packages/uSync.Complete/13.0.0-rc3
