### ISSUE TITLE
Health check errors out when uSync root folder doesn't exist

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#214]
**Describe the bug**
Possibly unhandled rejection: {"errorMsg":"Failed to retrieve status for health check with ID 018efc64-51bb-479b-ad09-73f538a1421a","data":{"ExceptionMessage":"Could not find a part of the path 'C:\\Websites\\U13\\uSync\\'.","ExceptionType":null,"StackTrace":null},"status":500,"xhrStatus":"complete"}

**Version (please complete the following information):**
 - Umbraco Version: 13 RC3
 - uSync.Complete Version: 13 RC2

**To Reproduce**
1. Make sure the RootFolder set in uSync config doesn't exist.
2. Run health check in Umbraco.
3. Health check hangs, in dev console the above error is logged.

**Comment by KevinJump** [comment]
fixed for next uSync release.
