### ISSUE TITLE
Question about licence domains

### ISSUE THREAD

**Issue by ianleeder** [Jumoo/uSync.Complete.Issues#227]
Can I clarify when the licence domain name is checked?  On my local development machine, it clearly says my licence is valid:
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/8241300/ec36c237-2d57-45bd-9807-d746963786dc)

Even though my dev machine is _not_ running on a licenced domain.  I have used my local to push to other instances of uSync that _are_ running on the licenced domains.  However I can't do the reverse: connect from a licenced domain back to my development machine.  Is this due to licence restrictions?

**Comment by ianleeder** [comment]
Weird.  Even though I'm well across the `baseUrl` setting and I tried every option under the sun, it didn't work.  However setting `"IncludeHost": false` worked, so it's not the licence.

It would be nice to know the URL that uSync uses for the Publisher handshake.  The best I could find is what's shown under the uSync Publisher Current Server, but it's definitely not that URL.  Partly because I'm not forwarding HTTPS.  
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/8241300/2bada4ec-e734-4656-b08c-f3df07d0a91f)

**Comment by KevinJump** [comment]
Hi, 

- when running local (localhost, .local, etc) the licence is checked to see if it's a valid licence, but the domain check isn't then ran as you are on a local box. 

- you can turn on verbose logging (https://docs.jumoo.co.uk/usync/uSync/guides/debugging#verbose-logging) that will show you what it happening with the handshake, it will show you how it builds up the key (including domain) so you can see what domain etc are being used by the calls.
