### ISSUE TITLE
Step returned false

### ISSUE THREAD

**Issue by itsliamprowse** [Jumoo/uSync.Complete.Issues#23]
**Describe the bug**
When having import on startup (or importing doc types from the models) turned on, we are unable to push or pull content, when we click on the send to server button it returns an error message "Step returned false" there is nothing in the logs to indicate any errors.

the content pushing worked fine until we used the import feature for the first time

This is a fresh install of Umbraco 8.5.5 with uSync.Complete 8.5.1

EDIT
It's worth noting that we're trying to achieve doc type and data types transfer via source control and content transferring via the back office

**Expected behavior**
for the content to be sent to the server

**Screenshots**
![image](https://user-images.githubusercontent.com/6665840/77639272-64f3fd80-6f50-11ea-9304-4178767baf5d.png)

**Comment by KevinJump** [comment]
Hi, thanks for the report

and sorry its not the most helpfull error message that one is it :( 

I think what is happening is that the publish process can't find any items to publish/check and that might be because the configuration is missing the set of handlers publisher uses. 

within your uSync8.config file you should have the following (below the default handler set entry)

      <Handlers Name="publisher">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="languageHandler" Enabled="true" Actions="All" />
        <Handler Alias="macroHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="templateHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All" />
        
        <Handler Alias="publishedContentHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTemplateHandler" Enabled="true" Actions="All" />
        <Handler Alias="dictionaryHandler" Enabled="true" Actions="All" />
        <Handler Alias="domainHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaHandler" Enabled="true" Actions="All" />
      </Handlers>
 
when you publish this is the group that gets used for syncing - if its not there then the default group gets used - and if things like contentHandlers are turned off, then nothing actually gets checked, and that is where the error is coming from :( ..

So we need a better error message, but i think if you have the section above exists in your uSync8.config file then it should start working again.

**Comment by itsliamprowse** [comment]
Ah thank you! turns out our pushishedContentHandler was set to false :) 
however now its not detecting any changes, its saying "No changes detected
It looks like everything is already in sync with the target. So you don't need to do anything"

**Comment by KevinJump** [comment]
:( are the others also set to true (e.g media etc) while you are syncing other things with the config, its probably best to keep all of these true, so the dependency tree can be calculated correctly. 

also remember it only syncs published changes by default, so if you change something and just save the node, that won't be pushed until it is published (you can change this behavior by swapping the PublishedContentHandler for a 'normal' content handler in the config).

**Comment by itsliamprowse** [comment]
All are set to true now, the doc types are being applied through the on startup successfully, however it still says that there are no changes (the content is definitely published) when we try and push content :(

**Comment by KevinJump** [comment]
Hi, can you check the usync config on the target server ? that too will need these changes, because it uses the same config elements to pull things in.

**Comment by itsliamprowse** [comment]
The configs are being sent through source control, so they are the same on both environments

**Comment by KevinJump** [comment]
Hi, 

I suspect its something similar to config not being quite right - I've pushed an updated version of the publisher package to give better messages.

```
Install-Package uSync.Publisher -Version 8.5.1.1
```

principally this checks to see if each folder that uSync passes to a server has a corresponding Handler on the server, if the handler is missing or isn't configured it should show up as a fail, with a message like: "No handler configured to process Content" 

If you can try this and give me a shout, it might help us get to the bottom of the issue.

**Comment by itsliamprowse** [comment]
Hey, 
Thanks for getting back to me, I have recreated the project with a new install of uSync and publisher version of 8.5.5.1 and we can now push content around happily, not quite sure why, all settings are the same as before :)

**Comment by KevinJump** [comment]
Cool Glad its working again. In theory 8.5.5.1 didn't have any changes in it other than better error reporting, but maybe that just reset things for you.

**Comment by KevinJump** [comment]
I think this is related to clientdependency cached scripts issue, in 8.6.0 we've put a warning into the code when this happens to encourage people to increment the version (which clears server/client cached pages).
