### ISSUE TITLE
Cannot add local Current Server - fails auth

### ISSUE THREAD

**Issue by ctolkien** [Jumoo/uSync.Complete.Issues#234]
When attempting to "Add this server", that being the current server, it fails with `Connection Test : Unauthorized`

AppId and Key have been set and double checked. Screenshot confirms it is there (and I've checked the config files)

Exact same code running locally works just fine. This is running in Azure Container Apps.

Umbraco 13. uSync latest for v13.

![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/515955/fa3fd858-c546-419a-ab46-674892ff818e)

![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/515955/cb43f0b5-037b-489c-8abd-e37e84690d20)

Documentation makes mention of setting a `baseUrl` in case the proxy is causing problems, but that doesn't appear to be a thing anymore. We are using forwarded headers in the MVC pipeline anyway.

**Comment by ctolkien** [comment]
Also worth pointing that I also cannot add this server from another host- fails with the same unauthorised error.

**Comment by KevinJump** [comment]
Hi, 

You can set the baseUrl, once the server is setup (so you can still set it up with a unauthorized result). 

one the server page if you go to the server advanced tab, there is a baseUrl value at the bottom. 

https://docs.jumoo.co.uk/usync/complete/setup/publisher/send#baseurl

_(my guess would be the certificate is applied in a diffrent place so the base needs to be http vs https)_

if that is still causing an issue you can set "IncludeHost" to false in the config.
(https://docs.jumoo.co.uk/usync/complete/setup/publisher/config#appsettingsjson-config-file) 
and then it won't care about the host name as part of the signing of the messages between servers (they are still using the appid/appkey just not the server name)

**Comment by ctolkien** [comment]
Setting includeHost to false has fixed it. The cert is definetly being applied closer to the edge than my app, however the fwd'd scheme headers should still have the request showing as being https.
