### ISSUE TITLE
Nit: Says pulling to, when it is pulling from..

### ISSUE THREAD

**Issue by ctolkien** [Jumoo/uSync.Complete.Issues#235]
First step: "Pull media from Dev"
<img width="356" alt="image" src="https://github.com/Jumoo/uSync.Complete.Issues/assets/515955/7421ccbc-d028-4f1d-92c6-bafe70979ea0">

Next Step: "pull _to_ Dev"

![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/515955/2c00eebe-0968-47ba-9807-47408df8be5a)

This sounds like it is pulling data into Dev, which isn't what I wanted, and isn't actually happening from what I can tell.

**Comment by KevinJump** [comment]
thanks, Will be fixed for next release (v13.2.x).

**Comment by ctolkien** [comment]
Here's another

<img width="250" alt="image" src="https://github.com/Jumoo/uSync.Complete.Issues/assets/515955/31446d3f-0a1d-41b9-a963-2fe3bf356af7">

**Comment by KevinJump** [comment]
Thanks, fixed.
