### ISSUE TITLE
Syncing user groups not working (as expected)

### ISSUE THREAD

**Issue by karltynan** [Jumoo/uSync.Complete.Issues#240]
## Describe the bug

User groups are not syncing to disc on save or export.

Clicking "Report" or "Export" shows as _Done_ in Umbraco and no files are generated.

This could be user error due to not understanding the documentation, but I have **uSync**,  **uSync Complete** AND **uSync People Edition** installed - it wasn't clear if I needed to install uSync and uSync People Edition for uSync Complete.

uSync settings: `appsettings.json`
```
"uSync": {
	"People": {
		"EnabledDefault": true
	},
	"Publisher": {
		...
	},
	"Settings": {
		"ImportAtStartup": "Settings",
		"ExportOnSave": "None",
		"UIEnabledGroups": "Settings,Users"
	},
	"Sets": {
		"Default": {
			"Handlers": {
				"DictionaryHandler": {
					"Group": "Settings",
					"Settings": {}
				}
			}
		}
	}
}
```
uSync settings: `appsettings.Development.json`
```
"uSync": {
	"Settings": {
		"ImportAtStartup": "None",
		"ExportOnSave": "Settings,Users"
	}
}
```

### Versions
 - Umbraco: 13.4.1
 - uSync: 13.2.5
 - uSync.Complete: 13.1.5
 - uSync.PeopleEdition: 13.1.5

### To Reproduce
1. Install the noted packages in Umbraco
2. Try to export user groups to disc, or
3. Try to save a change to user groups

### Expected behaviour
uSync would generate the files to be able to sync user groups between environments on save or export, much like content, settings etc.

### Actual behaviour
No files are generated on save or export. uSync reports as _Done_ when trying to "Report" or "Export" user groups. Neither approach generates any sync files.

#### Backoffice reporting:
![image](https://github.com/user-attachments/assets/892e539f-0100-4d3d-b451-3fb97e26040b)

#### Backoffice settings:
![image](https://github.com/user-attachments/assets/50add0f8-e946-40b9-bc26-e6db56379fdf)

#### Solution files:
![image](https://github.com/user-attachments/assets/abc44c47-e42b-4dbe-a7dc-f0006874d54f)

Many thanks in advance 😃

**Comment by KevinJump** [comment]
Yes. 

Looks like we updated some code and forgot to account for the fact the the default user is -1 and the root of the tree is also -1. 🤦 

fixed now. 

nightly release : https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync.Complete/overview/13.1.6-build.20240830.1

will package up next week, there are some other fixes in this. so we need to release note it up. 

Kevin

**Comment by karltynan** [comment]
Brilliant, thanks!

**Comment by karltynan** [comment]
Out of curiosity, do I need to install _uSync_ and _uSync People Edition_ as well as uSync Complete?

**Comment by KevinJump** [comment]
Hi,
 you should only need to install the usync.Complete package as that has dependencies on the other two (so they will be added automatically).
