### ISSUE TITLE
Toggle for varying document properties by culture, disappears when installing uSync.Complete

### ISSUE THREAD

**Issue by gab-trifork** [Jumoo/uSync.Complete.Issues#242]
**Describe the bug**
Installing uSync.Complete makes the "vary by culture" toggle on property level disappear.

**Version (please complete the following information):**
 - Umbraco Version: 14.2.0
 - uSync.Complete Version: 14.2.0
 - uSync Version: Not installed manually, Backoffice -> Settings -> uSync shows 14.2.1

**To Reproduce**
1. Create a new Umbraco 14.2.0 project: `dotnet new umbraco`
2. Install uSync.Complete: `dotnet add package uSync.Complete`
3. Start the server and go through initial Umbraco setup: `dotnet run`
4. Follow instructions for varying by culture (add language, create document type) (https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/variants)
5. When on the step `To allow a property on the Document Type to be varied it will have to be enabled for the property:` notice that there is no toggle for enabling "vary by culture" for the property.
6. Stop the server and uninstall uSync.Complete `dotnet remove package uSync.Complete`
7. Start the server again and the toggle is now there.

**Expected behavior**
The toggle is there letting me enable vary by culture for the property

**Screenshots**
I initially opened this issue on Umbraco-CMS GitHub, because I had overlooked that i has uSync.Complete as a depencency.
Might contain useful information (theres a few screenshots as well)
https://github.com/umbraco/Umbraco-CMS/issues/17111

**Comment by KevinJump** [comment]
Hi, 

Thanks for this, tracked it down and its fixed in v14.2.1 

https://www.nuget.org/packages/uSync.Complete/14.2.1

**Comment by KevinJump** [comment]
fixed in 14.2.1
