### ISSUE TITLE
Add config for fixed folders saved in static publisher

### ISSUE THREAD

**Issue by benjaminc** [Jumoo/uSync.Complete.Issues#30]
**Is your feature request related to a problem? Please describe.**
When I use the static publisher, it copies the static folders ~/css and ~/scripts, but I have a few additional folders I'd love to copy for my site.

**Describe the solution you'd like**
Add an entry to the server record in the uSync.Publish.config file, like was done for the "deployer" element, to specify which folders should be saved.

**Describe alternatives you've considered**
Another alternative might be to make the StaticSitePublisher class inheritable, with virtual methods, so that we could override just the GatherFiles method to customize the list ourselves.

**Comment by KevinJump** [comment]
will be in 8,7 release - https://github.com/Jumoo/uSync.Publisher.Static/commit/8d1b846bd2b096f59e0ff958f141947574b3239a
