### ISSUE TITLE
Add transforms for HTML content in static publisher

### ISSUE THREAD

**Issue by benjaminc** [Jumoo/uSync.Complete.Issues#31]
**Is your feature request related to a problem? Please describe.**
I have certain pages where, when I publish, I need to update access keys for third-party services.  I need a way to alter the saved HTML before it gets pushed to the destination.

**Describe the solution you'd like**
Create a new IHtmlTransform interface with a single method that takes the IContent object and the generated HTML content, and returns an updated HTML content.  Instances of this interface can be stored in dependency injection and loaded in the StaticSiteService as a collection.  Then in SaveHtml, after calling the GenerateItemHtml method, you call all the transforms.  If at the end, the HTML is null, you don't save that page.  Otherwise you save the transformed HTML.

**Describe alternatives you've considered**
Make all the methods in StaticSiteService virtual, so that we could extend that class and override the specific methods we want to update.  We could then override the GenerateItemHtml method to call the base version, then alter the returned HTML.  This is less ideal though because GenerateItemHtml doesn't get the IContent object, and so wouldn't know the content type or other properties of the object (which could make it hard to know when to make a change).

**Comment by benjaminc** [comment]
I'd be happy to provide a pull request for this, and #30, if there was a repository for the uSync.Publisher.Static project which I could be added to.

**Comment by KevinJump** [comment]
yep, to be honest, considering open sourcing the static publisher, so if i get around to that, then you are more than welcome to do the PR :)
