### ISSUE TITLE
Publishing media within folders

### ISSUE THREAD

**Issue by sstottelaar** [Jumoo/uSync.Complete.Issues#32]
**Describe the bug**
When publishing a folder with child items (media files) in the media library, the items get published but not within the designated folder. Everything gets put in the root of the media library on the targeted server.

**To Reproduce**
1. Go to Media
2. Create a new folder
3. Upload some media files to the created folder
4. Publish the folder to another server

**Expected behavior**
The folder gets created on the targeted server and the media items are put in the folder.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138

**uSync**:
- Version: v8.5.0.0

**Comment by KevinJump** [comment]
Hi, you should try this with the latest releases uSync (8.6.1) we did some work around parent folders for content and media, so content should never go into the root. but even without this it should work.  

If the new folder you create is beneath another folder that isn't on the target site, then without the 'include ancestors' setting ticked, the parent folder won't get sent over so there won't be a place to create it.  (the later fixes warn you of this too).

**Comment by sstottelaar** [comment]
I can confirm that updating to the last version as mentioned fixed this issue! Thanks for the help.
