### ISSUE TITLE
Package already installed error

### ISSUE THREAD

**Issue by peterjrichards** [Jumoo/uSync.Complete.Issues#33]
It looks to be an issue in Umbraco v8 when using version numbers with 4 parts.

1. Verify uSync.Complete is not already installed.
2. Clear down log files, i.e. delete JSON files under App_Data\Logs
3. Find and try to install package. Error is displayed
4. Look at logs for exact error

Attached are screenshots of the above steps and the Umbraco log file. I've changed the extension to .txt to allow it to be uploaded here.

[UmbracoTraceLog.20200526.txt](https://github.com/Jumoo/uSync.Complete.Issues/files/4681163/UmbracoTraceLog.20200526.txt)

![NotInstalled](https://user-images.githubusercontent.com/11010808/82883526-764e8b80-9f3a-11ea-8a17-8ea836e9153b.PNG)
![UnableToInstall](https://user-images.githubusercontent.com/11010808/82883530-76e72200-9f3a-11ea-9575-74be11717889.PNG)
![CleanedLogs](https://user-images.githubusercontent.com/11010808/82883531-76e72200-9f3a-11ea-8ac3-04f84036c9c1.PNG)
![Error](https://user-images.githubusercontent.com/11010808/82883532-777fb880-9f3a-11ea-8c5b-72e3ad167bfe.PNG)
![FindPackage](https://user-images.githubusercontent.com/11010808/82883533-777fb880-9f3a-11ea-927e-0ded6fa2fdd6.PNG)
![InvalidVersion](https://user-images.githubusercontent.com/11010808/82883534-777fb880-9f3a-11ea-8c56-f78722698999.PNG)

**Comment by KevinJump** [comment]
Hi yeah

Can you just confirm this is with the latest package version from our - we uploaded a new version a few days ago (called 8.6.1-not-1.zip) which has a package version of 8.6.1 (we took the .1 off it).

**Comment by peterjrichards** [comment]
Hi Kevin,

The package information states the version as 8.6.1.1 and the created date is 2020-01-07 so it could be the older version. I am not sure why the latest version is not being displayed in the Umbraco Backoffice packages list.

Many thanks,
Peter

**Comment by peterjrichards** [comment]
Having checked again today, it looks like the package has updated so the version is now 8.6.2 so this can be closed
