### ISSUE TITLE
Large transfers via Publisher

### ISSUE THREAD

**Issue by benjaminc** [Jumoo/uSync.Complete.Issues#50]
Transferring large amounts of content via Publisher can cause timeouts on either the source or destination, or can exceed the maximum file sizes allowed.  Additionally, if the network drops part of the way through, you can lose everything and have to restart.  There are a few things that would need to be done to circumvent this.

First, make publishing a background process, with the UI simply checking on the status of the process.  This would eliminate the request timeouts between the client and source system.

Second, once the publish package is constructed, break it into smaller pieces, the specific size should have a reasonable default of say 10 MB, but should be configurable on a per-publish-destination basis.  Transfer the package in pieces, and include code to try a transfer multiple times, with a reasonable delay between, in case the connection is going up and down.

This could reuse the same code which I'm proposing for Exporter in a separate feature request.  The publisher process could create an actual .usync file, then use the exporter's enhanced upload method to push it up, and finally trigger the import of the uploaded file.

**Comment by KevinJump** [comment]
Hi there is config that gets added to web.config to push the upload limits for publisher. see : https://docs.jumoo.co.uk/uSync/uSync.Complete/publisher/umbraco/

I would consider a 'large' publish to be more than 250 pages. not sure what your experience is. it depends a lot on what settings you are using (and something we are looking to streamline). 

In theory with everything else synced you don't need dependency checks, and parent checks etc, and that does make the syncs work a lot faster. 

but i agree with all of the above, we will look into it.
