### ISSUE TITLE
Create uSync.Publisher.Core package without UI and config components

### ISSUE THREAD

**Issue by benjaminc** [Jumoo/uSync.Complete.Issues#52]
For most of our clients we have a solution with at least two projects.  One contains Umbraco and is a web application, the other contains custom code, and is a DLL.  We like putting Publisher extensions in the DLL project, but each time we update it, it re-adds the App_Plugins and config folders, that we have to remember to delete.

The request is to create a .Core version of the uSync.Publisher package (and the uSync.ContentEdition package necessarily) that contains only the DLLs for the project, so that we can just reference this limited package in our DLL project.

**Comment by KevinJump** [comment]
will release a uSyncPublisher.Binaries package as part of next release. (prepping now)
