### ISSUE TITLE
Scheduled Publishing

### ISSUE THREAD

**Issue by poornimanayar** [Jumoo/uSync.Complete.Issues#53]
Hi Kevin,

I was wondering whether there are plans to add a scheduled publishing feature into uSync Publish? If I need to add scheduled publishing now I need to get the node unpublished to the target environment and schedule it there.

Poornima

**Comment by KevinJump** [comment]
yep, I think about it sometimes, but keep forgetting to add it here - lets add that to the list :)

**Comment by KevinJump** [comment]
feature is done 

will be in the next release of uSync/Complete - which we are starting to test now.
