### ISSUE TITLE
Import Document Type Missing, replaced with Import Sync-Pack

### ISSUE THREAD

**Issue by jattwood** [Jumoo/uSync.Complete.Issues#56]
On Usync 8.2.0 on Umbraco version 8.6.3, If I wish to import a document type when setting up my base environment, I can't see the Umbraco option to Import Document Type.

To reproduce, right mouse click on Document Types and you will see that there is only the option to Import Sync-Pack. If another umbraco install that I wish to get my doc type does not have Usync installed, I can't import any document type templates.

![image](https://user-images.githubusercontent.com/6452616/87165312-f9803280-c297-11ea-9018-fecccaa0fa45.png)

I would expect the default Umbraco Import Document Type as an option:

![image](https://user-images.githubusercontent.com/6452616/87165427-22082c80-c298-11ea-9dc3-5df9e4b9a6d3.png)

**Comment by KevinJump** [comment]
Hi, 

yes you can disable this feature by adding hte following to the uSync8.config file (and restarting the site)

```
<Backoffice>
    ///   ..... existing settings here ... 
   <Exporter>
     <DisableExistingMenuItems>false</DisableExistingMenuItems>
   </Exporter>
</Backoffice>
```

**Comment by jattwood** [comment]
Awesome. Thanks!
