### ISSUE TITLE
Add toggle to include all Dictionary Items in a sync pack.

### ISSUE THREAD

**Issue by KevinJump** [Jumoo/uSync.Complete.Issues#57]
When you create a syncpack via uSync.Exporter - Dictionary items directly referenced by a datatype or content type will be included in the sync. however if you want to include all dictionary items (becuase you use them in views etc) then you need a way to include them. 

The update adds a 'include dictionary' toggle to the export screen. this also includes languages. 

![image](https://user-images.githubusercontent.com/431231/90772070-0e66d180-e2ec-11ea-9748-ee807beaa538.png)

**Comment by lbras** [comment]
@KevinJump the "All Dictionary Items" toggle is no longer present in uSync.Exporter v8.11.8. Was it removed?

![image](https://user-images.githubusercontent.com/4013113/178272462-d93bd966-54bd-47ac-8d7e-08030863c78f.png)
