### ISSUE TITLE
Can't Export content

### ISSUE THREAD

**Issue by deMD** [Jumoo/uSync.Complete.Issues#59]
When trying to use the Exporter with a custom handlerset to export content and media a .bin file with a filesize of 0bytes is created instead of a .usync file. Additonally no content or media is exported when selecting f.e. mediatypes and media export.

**To Reproduce**
1. Add the Exporter option to usync.config:
`<Exporter>
      <HandlerSet>Exporter</HandlerSet>
    </Exporter>`
2. Copy the default handlerset and name the copy 'exporter'
3. Try to export content

Expected is a .usync file being created with the content in it, the result however is a .bin file of 0bytes in size.

![image](https://user-images.githubusercontent.com/22070292/94143493-31971a80-fe70-11ea-9683-a8a38a1f62f8.png)

OS: Windows 10
Browser: Firefox 81.0 (64-bit)
Version: Umbraco 8.6.2 Usync Complete 8.7.0.1

**Comment by KevinJump** [comment]
there was a rouge 'default' setting still in the code, so despite showing you the list of handlers from the correct group the exporter was still attempting to export using the default set and failing. 

fixed in 8.7.0.2 release
