### ISSUE TITLE
uSync Exporter import not importing content

### ISSUE THREAD

**Issue by deMD** [Jumoo/uSync.Complete.Issues#60]
After creating a usync package with content using the export function of uSync Exporter, the import function shows 0/0 changes when trying to import the content in an environment where the content doesn't exist. Also, when closing the import window an error is thrown

**To Reproduce**
1. Export content using uSync Exporter
2. Import that package in an environment where the content doesn't exsist.

**Expected behavior**
The content nodes are created.

**Screenshots**
![image](https://user-images.githubusercontent.com/22070292/94271643-32987c80-ff42-11ea-9fde-ae88d2735ffa.png)
![image](https://user-images.githubusercontent.com/22070292/94271742-56f45900-ff42-11ea-998a-c792dfe9c71f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 81.0 (64-bit)
 - Version Umbraco 8.6.2 uSync Exporter 8.7.0.3

**Additional context**
I am using a custom HandlerSet for Exporter.

**Comment by KevinJump** [comment]
Hi, 

if you open up the .usync file (it's a zip file, so renaming it to .zip will work fine for looking inside)- does it have a uSync/content folder (just checking its not an export issue).

**Comment by deMD** [comment]
It definitely contains content: 
![image](https://user-images.githubusercontent.com/22070292/94272365-40023680-ff43-11ea-924d-2e89e7640ac8.png)

**Comment by KevinJump** [comment]
Hi does the target site also have the `<exporter><handlerset>`.... setting in the config (and has it been restarted?)

**Comment by deMD** [comment]
It definitely has as I try to import it locally where I already added the exporter setting earlier.

**Comment by KevinJump** [comment]
yeah, just checking as i did that on my test setup - but my new test setup is behaving the same way as you site now, even though another site is actually importing the same sync file. .. still digging...

**Comment by KevinJump** [comment]
Its is totally possible that i fixed it and tested in debug and then built the previous release versions of the dlls into the nuget package 🤦‍♂️ 🤦 🤦‍♂️ 

https://www.nuget.org/packages/uSync.Exporter/8.7.0.4

this time including the latest compiled dll.

**Comment by deMD** [comment]
Time for weekend!!!

**Comment by KevinJump** [comment]
sounds like it.! - i haven't fixed the JS issue yet, but its not critical, its only if there if the dialog returns something which in this case it doesn't . so its not a show stopper.

**Comment by deMD** [comment]
Great, I'll check it out 👍

**Comment by deMD** [comment]
It's working! :) Thanks for fixing it so quickly #h5yr
