### ISSUE TITLE
Media not uploaded when using custom media folder name and/or azure storage

### ISSUE THREAD

**Issue by deMD** [Jumoo/uSync.Complete.Issues#63]
**Describe the bug**
When using uSync Exporter to export media with media files, files are exported properly, however when importing the usync package the files are not uploaded. We use Azure storage using the package https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure and a custom media folder name for each environment:
```
<location path="media-omg">
    <system.webServer>
      <handlers>
        <remove name="StaticFileHandler" />
        <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
      </handlers>
    </system.webServer>
  </location>
```
**Steps to reproduce**
Install usync complete
Install UmbracoFileSystemProviders.Azure
Use a custom media location
Export media
Import media

**Expected behavior**
Media is uploaded to Azure storage and linked to the imported media item.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 81.0.1

**Comment by KevinJump** [comment]
Hi, 

I just want to confirm i am setup right to test this. 

I have two sites, 
1. Source site is standard Umbraco install no azure (standard)
2. Target site is Umbraco site with UmbracoFileSystemProvider.Azure installed. 
web.config snipped for that is: 

```xml
<add key="AzureBlobFileSystem.ContainerName:media" value="jumoo-test-target-media" />
<add key="AzureBlobFileSystem.RootUrl:media" value="https://jumoodev.blob.core.windows.net/" />
```

With this exporting from source and importing to target works.
and exporting from target and importing to source works. 

Am i missing any extra steps to set this up ? have i missing a thing (i suspect i have!)

**Comment by deMD** [comment]
Hmm for me I use the UmbracoFileSystem.Azure on both sites with the following config:
```

**Comment by KevinJump** [comment]
for reference it looks like this is an issue inside the UmbracoFileSystemProvider.Azure project. 

when you have  useDefaultRoute = false, and your container name starts 'media' then there is a part of the azure file provider that cleans up the file name.  

https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/blob/adff24de3422377731720b94fe60e4544ba5afbf/src/UmbracoFileSystemProviders.Azure/AzureFileSystem.cs#L911

I think it shouldn't strip the `DefaultMediaRoute `value from the string if you are not using the default media route.
