### ISSUE TITLE
Missing quotes in uSync.Publish.config guidance

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#67]
There are a couple missing end quotes in the uSync.Publish.config comments which, whilst trivial, is annoying when you copy/paste into web.config!

line 13:
`<add key="uSync:Server" value="[serverAlias] />`

line 28:
`<add key="uSyncPublish:AppKey" value="AppKey />`

At least this issue is easy to fix ;-)

This is in latest v8.8.0

**Comment by LottePitcher** [comment]
But thank you for adding the ability to override these in appSettings: one less set of transforms to manage 🎉🤞

**Comment by KevinJump** [comment]
Fixed for the next release 😄  - also they are in the docs. 
https://docs.jumoo.co.uk/uSync/uSync.Complete/publisher/config/#webconfig-overrides
