### ISSUE TITLE
Add the ability to include content in sync packs/exports

### ISSUE THREAD

**Issue by Attackmonkey** [Jumoo/uSync.Complete.Issues#74]
Would it be possible to have the ability to include content in snapshots/exports?

Sometimes we might have instances where we want to pull content to somewhere that's not part of the regular pipeline, say if we're experimenting with new features separately and we want to bring in the content, but we don't want the instance we're playing around on to be part of the normal pipeline, as we might be making breaking changes.

It would also allow us to send the content to developers to work with locally when they don't have access to the production servers etc and they want to update their local sites with the latest content from live.

**Comment by KevinJump** [comment]
Hi, by default the exporter will show the active handlers, so if the content handlers are disabled then they don't show up in the exporter list.

However. you can add a setting to make the exporter use its own handler set. 
in the uSync8.config file. 

1. Add to handler groups
```
<Handlers Name="exporter">
  <Handler Alias="dataTypeHandler" Enabled="true" />
  <Handler Alias="languageHandler" Enabled="true" />
  <Handler Alias="macroHandler" Enabled="true" />
  <Handler Alias="mediaTypeHandler" Enabled="true" />
  <Handler Alias="memberTypeHandler" Enabled="false" />
  <Handler Alias="templateHandler" Enabled="true" />
  <Handler Alias="contentTypeHandler" Enabled="true" />
  <Handler Alias="contentHandler" Enabled="true" />
  <Handler Alias="contentTemplateHandler" Enabled="true" />
  <Handler Alias="dictionaryHandler" Enabled="true" />
  <Handler Alias="domainHandler" Enabled="true" />
  <Handler Alias="mediaHandler" Enabled="true" />
  <Handler Alias="memberGroupHandler" Enabled="true" />
  <Handler Alias="memberHandler" Enabled="true" />
  <Handler Alias="publicAccessHandler" Enabled="true" />
  <Handler Alias="userGroupHandler" Enabled="true" />
  <Handler Alias="userHandler" Enabled="true" />
</Handlers>
```

2. add to root of config file
```
<Exporter>
   <HandlerSet>Exporter</HandlerSet>
</Exporter>
```

**Comment by Attackmonkey** [comment]
Spot on, that worked like a charm, thank you! :)
