### ISSUE TITLE
"desaster" typo

### ISSUE THREAD

**Issue by glombek** [Jumoo/uSync.Complete.Issues#76]
**Describe the bug**
Not a major issue, just that "disaster recovery" is spelt "desaster recovery".

**To Reproduce**
1. Push content to another server
2. All instances where it should say "disaster recovery" it reads "desaster recovery"

**Comment by KevinJump** [comment]
Hi, 

I am not sure this is in uSync.Complete - i just did a quick search of the code and i don't think we say 'desaster' anywhere (although i won't put it pass me, it a very scouse sounding way to say it 😄 )
