### ISSUE TITLE
usync Package with just settings

### ISSUE THREAD

**Issue by loriRyanp** [Jumoo/uSync.Complete.Issues#82]
Is it possible to create just a package with just a projects settings.
Similar to usync publisher, settings, pull settings.
Its something we want to have as part of our github repo.
Content should never be part of it.

**Comment by KevinJump** [comment]
Hi, 

You have a couple of options. 

-  You can use the core uSync product to save only the settings to the uSync/v8 folder - by disabling the content related handlers in the uSync8.config / `default` handler group (uSync.Publisher uses the `publisher` handler group - so as long as the handlers are still enabled in that group - publisher will continue to work)

e.g.

```
 <Handlers Name="default">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="languageHandler" Enabled="true" Actions="All" />
        <Handler Alias="macroHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="templateHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All" />

        <!-- you might want dictionary items in settings ? -- >
        <!-- https://docs.jumoo.co.uk/uSync/v8/uSync/handlers/#handler-specific-settings if you want it to only sync new things -->     <Handler Alias="dictionaryHandler" Enabled="true" Actions="All" />

        <!-- content / members / users - all turned off -->
        <Handler Alias="contentHandler" Enabled="false" Actions="All" />
        <Handler Alias="contentTemplateHandler" Enabled="false" Actions="All" />
        <Handler Alias="domainHandler" Enabled="false" Actions="All" />
        <Handler Alias="mediaHandler" Enabled="false" Actions="All" />
        <Handler Alias="memberHandler" Enabled="false" Actions="All" />
        <Handler Alias="memberGroupHandler" Enabled="false" Actions="All" />
        <Handler Alias="userHandler" Enabled="false" Actions="All" />
        <Handler Alias="userGroupHandler" Enabled="false" Actions="All" />
      </Handlers>
```

or 

 - You can create a sync pack from uSync.Exporter - selecting just the doctypes/datatypes etc, that you want to include, not the content. 

in terms of keeping settings in the repo the first option probably makes more sense - as it will automatically keep settings and files in sync.

**Comment by loriRyanp** [comment]
Thanks for coming back so quickly – think I go with the first option.
