### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by loriRyanp** [Jumoo/uSync.Complete.Issues#85]
Ive updated several document Types locally to turn on the Allow varying by culture. I now need to import in just the settings to a "UAT" db however when I do just import the setting it doesnt appear to be getting updated.

When I choose to update the content and the settings it does.

Is there a way to just update the doctypes Allow varying by culture without affecting the content?

Any help would be brill.

**Comment by KevinJump** [comment]
Hi, 

We need to look into this, but i have seen similar before (not with uSync) on some versions of v8 - if you change a doctype to vary by culture, Umbraco doesn't necessarily update the content to then put the values into the correct language elements (at least not in the database) we have code in the core uSync to cater for this on import, because the default values actually remain with no culture even though the content should have cultured values

i think maybe we might need to apply a similar fix on export so non-cultured values are infact copied to a default culture (if that is missing) - but this behavior can be a little odd. we might say, changing to vary by culture requires a content sync

**Comment by KevinJump** [comment]
Hi - 

I've been looking at this today - at the moment i can't quite recreate the issue. 

so i have done the following: 

1. got two sites in sync without varying by culture
2. updated a doctype to vary by culture 
3. also updated some properties on that doctype to vary by culture
4. published just the settings to the other site*. 

when i do this and look on the target site the content is in the default (en-us) language as expected ?

this was on latest Umbraco/uSync - more than willing to try on another version - 

- **What version of umbraco & uSync are you on ?**
- **Is this the same process you did - or is there missing/extra steps?**

*noticed there is an issue syncing languages on uSync.Complete 8.9 - but this doesn't effect the default language stuff.

**Comment by loriRyanp** [comment]
Hi Kevin
So I have one site that doesn’t have varying by culture.

Ive update a base site – that has all the doctypes with the varying by culture flags – along with the properties.

We have multi sites that inherit the same code base but varying content.

The problem is I need to update the site that doesn’t have multilingual on to have multilingual.

If I could assign the content on the base site to a language say en-ie (is that possible?), update the  doctypes via a sync without content with the varying by culture flag would that work?

Kindest Regards
Lori

**Comment by KevinJump** [comment]
OK, I will have a look on v8.6.4 of umbraco. that sounds very similar to what i just tried on a fresh install (Umbraco v8.11.1) - but i will double check and install v v8.6.4 site and see if i can see any diffrences.

**Comment by KevinJump** [comment]
Some results of testing: 

v8.11.1
![variants-Eight11One](https://user-images.githubusercontent.com/431231/107360987-93c68400-6ace-11eb-8184-ab0fa265f003.gif)

v8.6.4: (same thing)
![variants-eightsixfour](https://user-images.githubusercontent.com/431231/107361805-d76dbd80-6acf-11eb-9642-cf0dc3e9540e.gif)

Just to confirm is this what you are expecting to happen ? (indeed does this happen when you do it? there might be another issue somewhere 😞  )

or do you want the content in all variants ? - (in these examples it goes into the default language)

**Comment by loriRyanp** [comment]
Thanks am just completely documenting to confirm with one page

**Comment by KevinJump** [comment]
Hi, 

this is fixed in 8.9.1 (Just released)
