### ISSUE TITLE
Images - physical files not appearing in media folder

### ISSUE THREAD

**Issue by loriRyanp** [Jumoo/uSync.Complete.Issues#86]
Just updated to usync 8.9 - when I am doing a sync now - the images dont seem to sync across. Having to manually copy files across. 
Looking in the usync config 

`<?xml version="1.0" encoding="utf-8"?>
<uSync>
  <BackOffice>
    <Folder>~/uSync/v8/</Folder>
    <FlatFolders>True</FlatFolders>
    <ImportAtStartup>False</ImportAtStartup>
    <ExportAtStartup>False</ExportAtStartup>
    <ExportOnSave>True</ExportOnSave>
    <UseGuidFilenames>False</UseGuidFilenames>
    <BatchSave>False</BatchSave>
    
    <RebuildCacheOnCompletion>False</RebuildCacheOnCompletion>
    
    <HandlerSets default="default" Default="default">
      <Handlers Name="default">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="languageHandler" Enabled="true" Actions="All"/>
        <Handler Alias="macroHandler" Enabled="true" Actions="All"/>
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="templateHandler" Enabled="true" Actions="All"/>
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="contentHandler" Enabled="true" Actions="All"/>
        <Handler Alias="contentTemplateHandler" Enabled="true" Actions="All"/>
        <Handler Alias="dictionaryHandler" Enabled="true" Actions="All"/>
        <Handler Alias="domainHandler" Enabled="false" Actions="All"/>
        <Handler Alias="mediaHandler" Enabled="true" Actions="All"/>
        <Handler Alias="memberHandler" Enabled="false"/>
        <Handler Alias="memberGroupHandler" Enabled="false"/>
        <Handler Alias="userHandler" Enabled="false"/>
        <Handler Alias="userGroupHandler" Enabled="false"/>
      </Handlers>
      <Handlers Name="publisher">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="languageHandler" Enabled="true" Actions="All"/>
        <Handler Alias="macroHandler" Enabled="true" Actions="All"/>
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All"/>
        <Handler Alias="templateHandler" Enabled="true" Actions="All"/>
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All"/>
        
        <Handler Alias="publishedContentHandler" Enabled="true" Actions="All"/>
        <Handler Alias="contentTemplateHandler" Enabled="true" Actions="All"/>
        <Handler Alias="dictionaryHandler" Enabled="true" Actions="All"/>
        <Handler Alias="domainHandler" Enabled="true" Actions="All"/>
        <Handler Alias="mediaHandler" Enabled="true" Actions="All"/>
        <Handler Alias="publicAccessHandler" Enabled="true" Actions="All"/>
        <Handler Alias="mediaFileHandler" Enabled="true" Actions="All">
          <Add Key="IncludeFileHash" Value="true"/>
        </Handler>
      </Handlers>
    </HandlerSets>
    <ReportDebug>False</ReportDebug>
    <FailOnMissingParent>True</FailOnMissingParent>
    <ShowVersionCheckWarning>True</ShowVersionCheckWarning>
  </BackOffice>
</uSync>`

**Comment by KevinJump** [comment]
Hi, 

are your images, on disk with the site, or in some remote storage (like azure blobs or s3) ? these should work, but likely a place the config might need tweaking.

**Comment by loriRyanp** [comment]
Hi Kevin
Just in the media folder on dsik within the site

**Comment by KevinJump** [comment]
:( 

is the `xxxxxx\media` path valid for your site ?

**Comment by loriRyanp** [comment]
media folder is C:\xxx\Umbraco\xxx\Media is correct path.

**Comment by KevinJump** [comment]
Is this from a publish from one site to another (in publisher) or a sync (usync dashboard import) or an export/import (in the exporter tab)

**Comment by loriRyanp** [comment]
usync exporter

**Comment by KevinJump** [comment]
OK, can you open up the .syncpack file (its a zip file, so you should be able to open it with something like 7zip or winzip. and see if it has the media folder in it (just want to check they are being exported)

**Comment by KevinJump** [comment]
(feel free to email me a sample syncpack file if that is easier kevin@jumoo.co.uk)

**Comment by KevinJump** [comment]
Hi, 

this is fixed in 8.9.1 (Just released)
