### ISSUE TITLE
Exception occurs when trying to pull content from remote server (Launched from the "Content" start node)

### ISSUE THREAD

**Issue by netaddicts** [Jumoo/uSync.Complete.Issues#89]
**Describe the bug**
Exception has occured when trying to pull content from a remote server. Remote servers are setup and available (status of the remote server is fine). (See screenshots of exact error message)

**To Reproduce**
1. Right-click the "Content" node in the content section
2. Select "Pull content"
3. Select remote server

**Expected behavior**
Expected to get the content from remote server, but got stuck at the calculation phase

**Screenshots**
<img width="413" alt="error-on-calculation-phase" src="https://user-images.githubusercontent.com/1563658/109772587-73d23e00-7bfe-11eb-94ab-d889eaa271cd.PNG">
<img width="1792" alt="detailed-error-message" src="https://user-images.githubusercontent.com/1563658/109772602-7896f200-7bfe-11eb-8972-b67437c40fd4.PNG">

**Desktop (please complete the following information):**
Windows 10 64bit, Firefox 86.0, uSync v8.8.3.0 + Content Edition, Snapshots, Exporter, PeopleEdition, Publisher, Complete

**Additional context**
Happens on environments that didn't have content yet (starting site from scratch and pulling content from remote server) as for environments already having content (either locally created or pulled from other environments). Didn't experience the issue pulling content for other nodes in the content tree

**Comment by KevinJump** [comment]
Hi - We'll take a look, see if we can replicate - 

can you see if there are any errors in the logs on the source server ?

**Comment by KevinJump** [comment]
Hi, we've tracked this down ... really annoying small javascript issue only on root content pulls. We will have a patch out soon.

for info: its a small change in a js file. uSyncPublishActionManager.js 

```js
function makeUdi(type, guid) {
  var key = guid !== undefined ? guid : '00000000-0000-0000-0000-000000000000';
  return 'umb://' + type + '/' + key;
}
```

becomes

```js
 function makeUdi(type, guid) {
   var entityType = type !== 'content' ? type : 'document';
   var key = guid !== undefined ? guid : '00000000-0000-0000-0000-000000000000';
   return 'umb://' + entityType + '/' + key;
}
```

We'll just check there is isn't anything else due in the next patch release and push it out.

**Comment by netaddicts** [comment]
thanks for looking into it, we can wait for the patch release or a minor/major release, not a blocking issue for us, just wanted to report as we had introduced a new dev to setup his local environment and perform a full sync from dev to local (we were able to do using snapshot feature)

**Comment by KevinJump** [comment]
Cool, we will patch shortly, - a full sync from the settings/publisher/server dialog will work, (because that just assumes the right UDI format when you tick the content box. but directly from content has this issue. 

![image](https://user-images.githubusercontent.com/431231/109800268-dcc4b080-7c14-11eb-932f-d8c46c247cb8.png)

**Comment by netaddicts** [comment]
Slightly (hmm, completely) unrelated... support for block list editor (especially media used in any of the block list components) is not yet supported, or do we need to develop a custom mapper?

**Comment by KevinJump** [comment]
It should be.. I certainly remember doing it. I will check.

**Comment by KevinJump** [comment]
We have a mapper in ContentEdition (see https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.ContentEdition/Mapping/Mappers/BlockListMapper.cs#L65) I will run some more tests locally and check that it is picking up all media/content used in items.
