### ISSUE TITLE
support for block list editor

### ISSUE THREAD

**Issue by KevinJump** [Jumoo/uSync.Complete.Issues#90]
Slightly (hmm, completely) unrelated... support for block list editor (especially media used in any of the block list components) is not yet supported, or do we need to develop a custom mapper?

_Originally posted by @netaddicts in https://github.com/Jumoo/uSync.Complete.Issues/issues/89#issuecomment-789654867_

**Comment by KevinJump** [comment]
Moving to new issue - for cleanlness :)

**Comment by netaddicts** [comment]
Just did a little test.. Having both DEV/TEST, first **pushed** item from DEV to TEST, missing media in block list editor, then **pulled** same item from DEV to TEST, all media except for one item wasn't pulled... I'll do some more push/pull this afternoon to verify if I can reproduce this behaviour consistently

**Comment by KevinJump** [comment]
OK, 

what type of elements are the media items in (e.g pickers, rte ect) - just done some quick tests locally (Umbraco 8.11.1 - uSync 8.8.3) and the media is being picked up. 

check to see what media is being reported - (e.g does the report box say its found the media) - just incase its a media import issue. 
![image](https://user-images.githubusercontent.com/431231/109802468-c409ca00-7c17-11eb-95c3-0ac8b4d5bebc.png)

**Comment by KevinJump** [comment]
if you want to send over any config / files (you could export as a sync pack). i can take a detailed look - locally i can get nested content blocks to include media, but i don't know how complicated/deep you are going. kevin@jumoo.co.uk if you want send anything.

**Comment by netaddicts** [comment]
Ok, me going through it again this afternoon, will report back if i can see something in the report too

**Comment by netaddicts** [comment]
> 
> 
> if you want to send over any config / files (you could export as a sync pack). i can take a detailed look - locally i can get nested content blocks to include media, but i don't know how complicated/deep you are going. [kevin@jumoo.co.uk](mailto:kevin@jumoo.co.uk) if you want send anything.

I can provide you with some credentials to logon (it's not production ready yet, so no big deal to create a user so you can have a quick look)

**Comment by KevinJump** [comment]
cool, feel free to drop us an email.

**Comment by netaddicts** [comment]
I'll first need to prepare a new content item in DEV, so we can perform the same actions and see what is going on

**Comment by netaddicts** [comment]
> 
> 
> cool, feel free to drop us an email.

Remind me again what email to use :)

**Comment by KevinJump** [comment]
kevin@jumoo.co.uk

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️

_note: block list support has been in for a while now, so hopefully this is ok_
