### ISSUE TITLE
xx items where updated 

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#92]
**Describe the bug**

"xx items where updated" should be "xx items were updated".

**To Reproduce**
Push or pull content

**Additional context**
uSync 8.9.1

**Comment by Nuklon** [comment]
One more typo:

Select a server
Pull content to Test

Should be:
Pull content from Test

**Comment by KevinJump** [comment]
thanks - fixed for next release.
