### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by lori698** [Jumoo/uSync.Complete.Issues#94]
I have an image cropper on Home -> news -> news article.

The images on news article never get imported. 
Could I email a sync pack to you - maybe you could advise?

**Comment by KevinJump** [comment]
hi yes send over the sync pack to kevin@jumoo.co.uk  -  i think there is a setting / config thing but i might have to refresh my memory

**Comment by KevinJump** [comment]
Hi, 

We think we have found the issue. just testing an update to make sure its fixed for the upcoming release.

**Comment by KevinJump** [comment]
Hi, this should be fixed now, but you will need to generate a new export as that will have been missing the file.

**Comment by KevinJump** [comment]
Hi, 

**also you will need to add the mediaFile handler to your config groups!** 

```
<Handler Alias="mediaFileHandler" Enabled="true" />
```

as this is what picks up the inline media items.
