### ISSUE TITLE
Publisher authentication works one way, but fails in the other

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#97]
Currently we have a test environment and a staging environment. We are using shared API keys which are configured in `web.config`, not in `uSync.Publisher.Config`

Staging can "see" test, and we can pull from Test to get content onto Staging (so surely the API keys are correct?).
However Test cannot "see" Staging, it reports unauthorized access, so of course we can't push from Test to Staging.

Staging has https offloaded. The url property is set to the https version, and the baseUrl set to the non http version.

We have 4 very similar sites. All 4 test sites are on the same EC2 server. The staging sites are in separate, but similarly configured environments (i.e. all staging sites have https offloaded).

Site 1 - uSync.Core 8.8.1, uSync.Publisher **8.8.1**, Staging can see Test ✔️, Test can see Staging ✔️ 
Site 2 - uSync.Core 8.8.3, uSync.Publisher **8.8.3**, Staging can see Test ✔️, Test can see Staging ✔️ 
Site 3 - uSync.Core 8.8.3, uSync.Publisher **8.9.1**, Staging can see Test ✔️, Test cannot see Staging ⛔ 
Site 4 - uSync.Core 8.8.4, uSync.Publisher **8.9.2**, Staging can see Test ✔️, Test cannot see Staging ⛔

Whilst I appreciate this might be some misconfiguration somewhere in environments 3 and 4, I just wanted to check with you in case anything occurred to you about what might be the cause, especially considering they are both on the later Publisher version.

Many thanks!

**Comment by KevinJump** [comment]
Hi, 

The verbose logging has a bit more info in it - so it should help get to the bottom of this 🤞

**Comment by LottePitcher** [comment]
@KevinJump thanks Kevin! We have upgraded to v8.9.5 and this has indeed fixed the problem
