### ISSUE TITLE
Ignore both colour pickers and grid settings

### ISSUE THREAD

**Issue by lori698** [Jumoo/uSync.Complete.Issues#98]
Hi Kevin 
Just tweaking and need to now ignore grid settings i.e. row configurations.
Was looking at the documentation it just says 
List of editor aliases of items you don't want the configuration to be imported for.
But unsure of the delimiter.
Is there a better way to exclude the grid settings.
Thanks as always for the help

Ive tried the below but I dont think its right. 
```
 <Handler Alias="dataTypeHandler" Enabled="true" Actions="All">
          <Add Key="NoConfigEditors" Value="Umbraco.ColorPicker, Umbraco.Grid" />
        
        </Handler>
```

**Comment by KevinJump** [comment]
Hi 
 it is comma delimited, and that setup should work (I've just tested locally and it works for me - updated grid settings are not synced). 

updated to the settings will be saved out to the files on disk - but they will not be imported.

**Comment by lori698** [comment]
ok thanks I check again. Once again kevin quick response is epically good.
Is there something I could drop some money to get you a coffee or something like that? 
Thanks again
